### ISSUE TITLE
[Doc] Add default value of crawlerOptions.limit to /crawl documentation

### ISSUE THREAD

**Issue by rafaelsideguide** [mendableai/firecrawl#107]
"Show the default value of crawlerOptions.limit in https://docs.firecrawl.dev/api-reference/endpoint/crawl. Judging from the code itself it looks like it's set as 10000."

Suggested by @by12380 on Discord.

**Comment by nickscamara** [comment]
https://github.com/hellofirecrawl/docs/issues/1
