### ISSUE TITLE
Unable to run python sdk sample code from README

### ISSUE THREAD

**Issue by HowieG** [mendableai/firecrawl#123]
Traceback (most recent call last):
  File "/Users/howardgil/Desktop/Projects/nat-sec-hackathon/firecrawl.py", line 1, in <module>
    from firecrawl import FirecrawlApp
  File "/Users/howardgil/Desktop/Projects/nat-sec-hackathon/firecrawl.py", line 1, in <module>
    from firecrawl import FirecrawlApp
ImportError: cannot import name 'FirecrawlApp' from partially initialized module 'firecrawl' (most likely due to a circular import) (/Users/howardgil/Desktop/Projects/nat-sec-hackathon/firecrawl.py)

**Comment by calebpeffer** [comment]
Hey! May be because you importing firecrawl from a file named firecrawl. Python imports are a menace. hmu for more support 6034026101

**Comment by HowieG** [comment]
Yooo you're right lmao I renamed it to test.py and it worked. This is so funny bc I reported a similar issue with multion bc I named it multion.py I was like nothing works today 😭

**Comment by HowieG** [comment]
Closing
