### ISSUE TITLE
Get Code for LLM Extract returns bad JSON

### ISSUE THREAD

**Issue by HowieG** [mendableai/firecrawl#124]
I understand LLM Extract is in alpha and Get Code is likely nondeterministic so feel free to ignore. But this is what it gave me:
<img width="531" alt="Screenshot 2024-05-04 at 7 29 40 PM" src="https://github.com/mendableai/firecrawl/assets/15098079/72b2f51b-c84d-4e3f-9000-0a45397ed4df">

Which was missing a closing apos and some commas
<img width="1002" alt="Screenshot 2024-05-04 at 7 30 00 PM" src="https://github.com/mendableai/firecrawl/assets/15098079/f00bafa6-5a05-438b-94e7-f6b869b4206a">

Fixed JSON looked like this
<img width="1076" alt="Screenshot 2024-05-04 at 7 30 51 PM" src="https://github.com/mendableai/firecrawl/assets/15098079/ad709ee1-247b-48e3-8a79-d0c0750c146d">

**Comment by hellofirecrawl** [comment]
Great callout! Will fix asap

**Comment by nickscamara** [comment]
Fixed! Thank you! @HowieG!
