### ISSUE TITLE
[Feat] Pagination on /crawl

### ISSUE THREAD

**Issue by rafaelsideguide** [mendableai/firecrawl#125]
suggested on Discord

**Comment by nickscamara** [comment]
Or is it to skip the results?

**Comment by rafaelsideguide** [comment]
"yea im looking into building a scraper that can get all product details from ecommerce site - so pagination is quite common" - JZ on Discord

I tested with page_num on [scrapethispage](https://www.scrapethissite.com/pages/forms/?page_num=2) and it's able to crawl with no problems. So I'm closing this one.
