### ISSUE TITLE
UI bug with Preview

### ISSUE THREAD

**Issue by HowieG** [mendableai/firecrawl#128]
Lots of space before the result in Preview in this one case

<img width="1281" alt="Screenshot_2024-05-04_at_19 47 22" src="https://github.com/mendableai/firecrawl/assets/15098079/5152ecee-7226-4f0c-bbc0-352c3f9e1186">
<img width="1234" alt="Screenshot_2024-05-04_at_19 47 25" src="https://github.com/mendableai/firecrawl/assets/15098079/989aec28-37f3-4312-8fc5-13e05c0c9533">

**Comment by nickscamara** [comment]
Great feedback, fixing this today!
