### ISSUE TITLE
Feat: Support gathering content within Iframes

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#136]
In some pages, content is stored within an Iframe.

I recommend using a playwright to handle this. This is dependent on the incoming fc-scraper release @nickscamara @rafaelsideguide

**Comment by rafaelsideguide** [comment]
This feature request has been inactive for 28 days and was not prioritized. We are closing it for now. If this feature becomes a priority in the future, please feel free to reopen or submit a new request.

**Comment by calebpeffer** [comment]
Opening again: This has been asked about a few times.

**Comment by nickscamara** [comment]
Released today! Fixed!
