### ISSUE TITLE
[Test] Add integration tests for complex and larger variety of webpages

### ISSUE THREAD

**Issue by oliviermills** [mendableai/firecrawl#15]
In tweaking and growing the html clean up and html-to-md. I highly recommend adding integration tests using either live webpages (to test also the get/network and dynamic websites) OR at least saved html pages with complex layout (and bad html, especially for the html clean up.
 - [ ] Find a list of pages to use as test suite with a vareity of layouts
 - [ ] Add the integration tests

**Comment by nickscamara** [comment]
- Add more specific tests like h1 -> # 
- Get a list of website -> markdown small dataset
-

**Comment by rafaelsideguide** [comment]
Closing this one (related to #118)
