### ISSUE TITLE
Python SDK cannot work with local install

### ISSUE THREAD

**Issue by mattjoyce** [mendableai/firecrawl#164]
The Python SDK cannot work with local installs because the API URL hostname is hard coded to : https://api.firecrawl.dev.

**Comment by mattjoyce** [comment]
I have added an optional parameter which defaults to https://api.firecrawl.dev/, but will will detect FIRECRAWL_API_URL and use that if present.

**Comment by mattjoyce** [comment]
https://github.com/mendableai/firecrawl/pull/166

**Comment by nickscamara** [comment]
Just merged! Thank you Matt!
