### ISSUE TITLE
Crawl API fails for local installation

### ISSUE THREAD

**Issue by mattjoyce** [mendableai/firecrawl#165]
After installing locally using Docker, I cannot get crawl to work.   "Failed to bill team, no subscription was found"
Scrape does work.

This is a typical response for Crawl via Curl or Python.

```
{
  "data": {
    "url": "https://github.com/mendableai/firecrawl",
    "mode": "crawl",
    "crawlerOptions": {},
    "pageOptions": {
      "onlyMainContent": true
    },
    "origin": "api"
  },
  "returnValue": {
    "success": false,
    "result": {
      "links": []
    },
    "error": "Failed to bill team, no subscription was found"
  }
}
```

**Comment by rafaelsideguide** [comment]
hey @mattjoyce have you set the USE_DB_AUTHENTICATION to `false` in the `apps/api/.env` file?

**Comment by mattjoyce** [comment]
Yes, without that the response is a 401.
Strange that Scrape works and Crawl does not, I assumed Scrape was a shallow single page crawl.
The specific erros only appears in 
[runWebScraper.ts](https://github.com/mendableai/firecrawl/blob/d5d0d488486caece6669fec7b4b84cc712a3248f/apps/api/src/main/runWebScraper.ts#L102)

I tried to work back from that, but my JS/TS is weak.  :(

**Comment by mattjoyce** [comment]
The Python binding, requires an API key, but there is no api key for local right, is that relevant?

**Comment by mattjoyce** [comment]
Ok, I just rebuild my local installation, and it works.
So I assume it was something in my docker file.
