### ISSUE TITLE
[BUG] Can't access content in readme api documentation

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#189]
**Describe the Bug**

Firecrawl fails to gather all the data available on documentation portals powered by Readme. 

Specifically, its not getting information such as query parameters in code snippets

**To Reproduce**
Just try scraping pages such as 

Asana: https://developers.asana.com/reference/getworkspaces

Bamboo HR: https://documentation.bamboohr.com/reference/time-off-add-a-time-off-request-1

Breezy HR: https://developer.breezy.hr/reference/company-position-update

Ashby: https://developers.ashbyhq.com/reference/jobcreate

**Expected Behavior**
This should gather the code, and other information in the sidebar.

**Additional Context**

I did some digging, and it seems like some of this data is available in the rawhtml.

<img width="1485" alt="image" src="https://github.com/mendableai/firecrawl/assets/44934913/4d2a536d-77bc-44e8-843f-1bd35c027c35">

But, its in a massive block of json, and is repeated over 296 times? Not really sure whats happening here:

<img width="1302" alt="image" src="https://github.com/mendableai/firecrawl/assets/44934913/57a4935f-faa0-435b-a705-5a9c233767e4">

Notify David Dalmaso in Slack and Aaron Tran via messenger when finished @calebpeffer

**Comment by rafaelsideguide** [comment]
Tested using the `waitFor: 500` and it was able to get the params from the asana docs page.
![Captura de Tela 2024-05-29 às 10 59 51](https://github.com/mendableai/firecrawl/assets/150964962/160a8f6d-e8b7-4583-bc11-684054c61273)

Should we implement a way to detect if it's a page powered by Readme? @nickscamara what do you think?
