### ISSUE TITLE
Docs: Add documentation for self hosting

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#19]
<img width="302" alt="image" src="https://github.com/mendableai/firecrawl/assets/44934913/de2951f3-015b-40a8-b882-0ed4478995ef">

**Comment by JackBlair87** [comment]
So true!!!

**Comment by rowbot1** [comment]
following

**Comment by bmwas** [comment]
following as well :+1:

**Comment by calebpeffer** [comment]
Hey all. We'd love to understand better what usecases you all want self-hosting for. It will help us design the architecture!

If you're interested in sharing, schedule a meeting with us here => [Talk to us](https://calendly.com/d/ckhk-292-byz/talk-to-the-maintainer-s)

We'll give shoutouts on twitter and the repo.

**Comment by JackBlair87** [comment]
I want to host locally and not on docker. Just a localhost port I can connect to and use. A lot like how ChromaDB does it.

**Comment by nickscamara** [comment]
Hey yall, we just merged self-hosting! Here are the quick docs for it [https://github.com/mendableai/firecrawl/blob/main/CONTRIBUTING.md](https://github.com/mendableai/firecrawl/blob/main/CONTRIBUTING.md)

Setup is super simple. Let us know if you have any questions. Excited to see yall contributing!

(#40 closes this)

**Comment by latentsauce** [comment]
@nickscamara thank you!!
