### ISSUE TITLE
[BUG] PIP Package is not deploying the latest Python SDK

### ISSUE THREAD

**Issue by mattjoyce** [mendableai/firecrawl#193]
The code deployed by PIP is not the latest.

Create a new venv and pip install firecrawl-py/
Compare the code in the venv with github, the pip installed code is old.

venv/lib/python3.12/site-packages/firecrawl/firecrawl.py
https://github.com/mendableai/firecrawl/blob/main/apps/python-sdk/firecrawl/firecrawl.py

I tried this on Windows and Linux

**Comment by mattjoyce** [comment]
Also, this is old too.
apps/python-sdk/build/lib/firecrawl/firecrawl.py

So I think something not right with last build.

**Comment by nickscamara** [comment]
Fixed! Thanks @mattjoyce

Also adding #194 to smooth the publishing process out.
