### ISSUE TITLE
[BUG] Search is returning "no page found" on self-host

### ISSUE THREAD

**Issue by rafaelsideguide** [mendableai/firecrawl#197]
**Describe the Bug**
Search is returning "no page found" on self-host

**Expected Behavior**
Should return result with content.

**Screenshots**
![image](https://github.com/mendableai/firecrawl/assets/150964962/69ca5885-31e7-4003-bec5-42bc6a549bf0)

**Additional Context**
from Discord

**Comment by mattjoyce** [comment]
Ok, so this does not work.

```
payload = {
    "url": "https://www.humblebundle.com/",
    "pageOptions": {
        "includeHtml": True,
        "waitFor": 123,        
        "onlyMainContent": True,
    }
}
```

but this does.

```
payload = {
    "url": "https://mendable.ai",
    "pageOptions": {
        "onlyMainContent": True,
        "includeHtml": True,
        "waitFor": 123
    }
}
```
in the Docker logs we see this.

> api-1                 | Error fetching w/ playwright server -> URL: https://www.humblebundle.com/ with status: 404
> api-1                 | Falling back to playwright
> api-1                 | Falling back to scrapingBeeLoad
> api-1                 | **Falling back to fetch**
> api-1                 | Error: Error: All scraping methods failed for URL: https://www.humblebundle.com/ - Failed to fetch URL: https://www.humblebundle.com/

and this

> api-1                 | Error fetching w/ playwright server -> URL: https://mendable.ai with status: 404
> api-1                 | Falling back to playwright
> api-1                 | Falling back to scrapingBeeLoad

**Comment by mattjoyce** [comment]
@rafaelsideguide , I see a lot of these, every scrape actually.
> api-1 | Error fetching w/ playwright server -> URL: https://www.humblebundle.com/ with status: 404

and 'Page Cannot Be Found' is really 'All scraping methods failed'

Seems related to : https://github.com/mendableai/firecrawl/issues/179

**Comment by rafaelsideguide** [comment]
@mattjoyce is this solved?

**Comment by mattjoyce** [comment]
@rafaelsideguide yes, pretty sure that is fixed by that patch.

```
app = FirecrawlApp(api_url="http://localhost:3002")
url = "https://www.humblebundle.com"
params={"pageOptions": {
        "includeHtml": False,
        "waitFor": 123,        
        "onlyMainContent": True,}}
scraped_data = app.scrape_url(url,params=params)
```

Works for me, I just fetched main.

**Comment by rafaelsideguide** [comment]
@mattjoyce thanks! I'll close this one.
