### ISSUE TITLE
[Feat] Return computed styles

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#203]
**Problem Description**
In certain circumstances, it's useful to grab computed styles from a page. Currently, this is impossible via fire crawl

**Proposed Feature**

Firecrawl returns a computed styles object when a parameter is passed

**Alternatives Considered**
Is there a way for us to pass through more p

**Implementation Suggestions**
Playwright has a "getComputedStyle" method https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle. However, Idk if this would work without a traversal. There may be an easier way

**Use Case**
This would be useful for situations where the computed styles matter. Such as web agents or A/B testing tools

**Additional Context**

When complete, notify GB via slack @calebpeffer

**Comment by nickscamara** [comment]
Marking as blocked for now as not needed immediately.

**Comment by rafaelsideguide** [comment]
Closing this as it hasn't been prioritized and has remained "stale" since June 14th.
