### ISSUE TITLE
[sdk] Timeout param in crawl is confusing

### ISSUE THREAD

**Issue by nickscamara** [mendableai/firecrawl#208]
Timeout param in crawl is confusing as it refers to the how long it waits until it checks for crawl status instead of being the timeout of the crawl itself. We should rename it.

**Comment by mattjoyce** [comment]
The purpose of the parameter is to set the period between checks, so...(check, poll, status) x ( period, interval, frequency)
    check-period
    check-interval
    check-frequency
    poll-period
    poll-interval
    poll-frequency
    status-period
    status-interval
    status-frequency

**Comment by nickscamara** [comment]
yep. poll interval or polling interval works great!
