### ISSUE TITLE
[BUG] Broken Link => https://www.safework.nsw.gov.au/

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#219]
Issue 1: Inability to Crawl Site https://www.safework.nsw.gov.au/
Firecrawl is unable to crawl the site https://www.safework.nsw.gov.au/ and extract the main contents. The issue also includes difficulties in extracting data from associated PDFs.

**To Reproduce**
Steps to reproduce the issue:

**Configure the environment or settings to crawl the site** https://www.safework.nsw.gov.au/.
Run the command to start crawling the site.
Observe the error or unexpected output indicating the crawl failure.
Log output/error message.
Expected Behavior
The crawler should successfully extract the main contents from the site and handle PDFs correctly. 

![image](https://github.com/mendableai/firecrawl/assets/44934913/656af9e3-4138-4864-a1da-4127eb5caf9f)

**Additional Context**
Customer attempted to crawl using Fast Mode and experienced consistent failure. Suggested settings modifications did not resolve the issue. Seems to **timeout**

**Comment by calebpeffer** [comment]
See #220 - seem's to be an infrastructure issue with the crawl stalling... happens on both https://www.safework.nsw.gov.au/ and clintonToyota (see #220)

Doesn't always occur.

**Comment by nickscamara** [comment]
Node running out of memory. Investigating why...

**Comment by nickscamara** [comment]
#225 is the issue

**Comment by nickscamara** [comment]
@calebpeffer Fixed!
