### ISSUE TITLE
[BUG] Inability to Crawl Subpages on https://www.clintonstoyota.com.au/

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#220]
Describe the Bug
Firecrawl is unable to crawl subpages of https://www.clintonstoyota.com.au/news/, https://www.clintonstoyota.com.au/new-vehicles/, and https://www.clintonstoyota.com.au/our-location/. Individual URLs are scraped correctly, but subpages remain inaccessible.

**To Reproduce**
Steps to reproduce the issue:

Configure the environment or settings to crawl the subpages of https://www.clintonstoyota.com.au/.
Run the command to start crawling the specified subpages.
Observe the error or unexpected output indicating the crawl failure.
Log output/error message.

**Expected Behavior**
The crawler should successfully extract data from all subpages of the specified URLs.

**Additional Context**
The customer reported that the crawler has been running for a prolonged period without successfully accessing the subpages.

**Comment by calebpeffer** [comment]
Updates. The issue is that the crawl is sometimes freezing in the middle of a website. Happening on https://www.clintonstoyota.com.au/

**Comment by nickscamara** [comment]
Node running out of memory. Investigating why...

**Comment by nickscamara** [comment]
#225 is the issue

**Comment by nickscamara** [comment]
@calebpeffer Fixed!
