### ISSUE TITLE
[docs] Improve the crawl_url docs about the python sdk

### ISSUE THREAD

**Issue by nickscamara** [mendableai/firecrawl#227]
Improve docs stating that the crawl_url in python sdk returns the results by default instead of the job id

**Comment by mattjoyce** [comment]
- Needs information about FIRECRAWL_API_URL.
- Timeout needs renaming to IntervalPolling to match JS SDK then docs need updating.

I will do.  Please assign.

**Comment by mattjoyce** [comment]
will need info on FIRECRAWL_LOGGING_LEVEL if implemented.
