### ISSUE TITLE
[BUG] Crawl on single page works on playground but fails via curl 

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#231]
**Describe the Bug**
For some odd reason, the using the crawl endpoint on this link [https://www.tripadvisor.com/Restaurant_Review-g60763-d4418144-Reviews-Reichenbach_Hall-New_York_City_New_York.html ](https://www.tripadvisor.com/Restaurant_Review-g60763-d4418144-Reviews-Reichenbach_Hall-New_York_City_New_York.html) returns a single page on the playground, but returns nothing via curl request
 
**To Reproduce**
Steps to reproduce the issue:
1. Run URL in Playground
2. Run /crawl via curl then hit the /getCrawl endpoint with the returned ID

**Expected Behavior**
This should return the content for a single page

**Screenshots**

The page working via playground:
<img width="1197" alt="Screenshot 2024-06-03 at 6 05 21 PM" src="https://github.com/mendableai/firecrawl/assets/44934913/9195ff26-9c5c-4ea3-bb31-921eafed0ad7">

The page failing via curl:
<img width="566" alt="336270082-0287cb4b-38a7-4555-be6b-b31ea8037f2e" src="https://github.com/mendableai/firecrawl/assets/150964962/447edeb0-dc3d-4f1d-9101-bff6049406fe">

**Additional Context**
Brought up by MN via email

**Comment by rafaelsideguide** [comment]
@calebpeffer is there any updates on this one?

**Comment by rafaelsideguide** [comment]
This is v0. Now, with v1, both the playground and API share the same behavior. This page doesn't have child links, `"allowBackwardLinks":true` fixes the crawl. Closing for now.
