### ISSUE TITLE
[Feat] Detect Distinct Sections in Webpages

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#241]
**Problem Description**
Users need to detect distinct sections within a webpage and have these sections represented in the markdown output.

**Proposed Feature**
Implement a feature that identifies distinct sections in a webpage and includes these sections in the markdown output.

**Use HTML structure (e.g., headings) to detect sections.**
Update the markdown generator to include section markers.
Use Case
It helps users navigate and understand content structure, making it easier to extract relevant information from long articles.

**Additional Context**
Similar to section detection in content management systems and markdown editors.

**Comment by rafaelsideguide** [comment]
Closing this one as #245 is a duplicate with more content on this topic
