### ISSUE TITLE
[Feat] option to remove cookie popups

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#243]
**Problem Description**
Customers often do not need cookie popups.

**Proposed Feature** 
Option to remove cookie popups perhaps.

**Alternatives Considered**
It may be better to have a more general filtering strategy that allows customers to define what types of content  to exclude 

**Implementation Suggestions**
There are 4 - 5 big cookie popup layouts (i.e. Wordpress). Hardcode regex for these. Another option would be removing repeated content across pages in the crawl but this would remove more.

**Use Case**
Users wouldn't have to filter this out themselves.

Thanks @AndyMik90 for the suggestion.

**Comment by nickscamara** [comment]
#78

**Comment by nickscamara** [comment]
We just pushed something #273 that helps with this! Closing this for now!
@AndyMik90 @calebpeffer
