### ISSUE TITLE
[Feat]  Implement Class-Based Logging in Python SDK

### ISSUE THREAD

**Issue by mattjoyce** [mendableai/firecrawl#254]
To enhance the SDK's maintainability and user experience by implementing class-based logging. 
This approach will allow internal SDK operations to be logged at a granular level, providing better diagnostics, debugging, and operational transparency without interfering with the host application's logging configurations.

**Background:**
Currently, the SDK might not fully encapsulate logging, potentially leading to conflicts with host application logging configurations or polluting global log files with SDK-specific messages. This can complicate the integration process for users and obscure important information with unnecessary log details.

**Proposed Solution:**

Logger Initialization: Each class within the SDK will initialize its own logger using Python's built-in logging module. This will be done by calling logging.getLogger(__name__) to ensure that each logger is specific to its class context.

Log Level Configuration: Provide flexibility by allowing log levels to be set via environment variables or directly within the SDK, making it easy to switch between detailed logging (for development) and less verbose logging (for production).

Handler and Formatter Setup (Optional): By default, loggers will not have a specific handler unless explicitly configured. This leaves the choice of log handling (e.g., file, console, external systems) up to the application developer using the SDK.

Disable Propagation: Set logger.propagate = False for all SDK loggers. This will prevent logs generated by the SDK from being propagated to the application's root logger, avoiding log duplication and ensuring that SDK logs do not interfere with the application's logging strategy.

Documentation: Update SDK documentation to clearly describe how logging is configured and how users can customize it to fit their needs.

**Benefits:**

Isolation: Prevents SDK logs from interfering with the host application’s logs, providing a cleaner integration experience.
Customizability: Users can easily adjust the logging level and configure specific handlers as needed without altering the SDK’s code.
Debugging and Maintenance: Facilitates better maintenance and debugging capabilities for developers working on the SDK or integrating it into their applications.

**Implementation Steps:**

Refactor existing logging implementations in the SDK to use class-specific loggers.
Provide configuration instructions in the documentation.
Add environment variable checks or configuration options for setting log levels.
Ensure comprehensive testing to validate that the new logging setup does not introduce any side effects in typical usage scenarios.

**Comment by mattjoyce** [comment]
@nickscamara if supportive, please assign to me, I have this basically implemented.
> def __init__(self, api_key: Optional[str] = None, api_url: Optional[str] = None, log_level: str = None) -> None:

**Comment by nickscamara** [comment]
Lovely! Go for it @mattjoyce!

**Comment by rafaelsideguide** [comment]
hey @mattjoyce is this one closed by #256 ?

**Comment by mattjoyce** [comment]
Yes, I will submit something similar for the playwright wrapper.
