### ISSUE TITLE
[BUG] Issue crawling all subpages on https://synctera.com/blog

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#257]
**Describe the Bug**
The customer wanted to crawl the entire pages on a website and generate a markdown file.

The parent site, https://synctera.com/blog, consists of like 100+ pages. But all it was crawling to were somewhere around 20+ pages only. 

**To Reproduce**
Run on https://synctera.com/blog

**Expected Behavior**
The crawler should return all pages, but instead it returns only ~20

**Additional Context**

Brought to our attention by @poojaOgupta - please notify her via krisp when solved @calebpeffer

**Comment by nickscamara** [comment]
Sitemap is incomplete, so it grabs the sitemap. finds the blog links there and return instead of crawling the /blog

**Comment by poojaOgupta** [comment]
@nickscamara is there any way to bypass this?

**Comment by nickscamara** [comment]
@poojaOgupta Yep! working on it :)

**Comment by poojaOgupta** [comment]
Alrighty. Thanks for the update @nickscamara. Please keep me posted 😁

**Comment by nickscamara** [comment]
Will do! I also just realized that all the blog posts are under baseUrl/post and not under blog/* haha. Which is strange and another reason it is causing issues... Still working on getting it working though

**Comment by nickscamara** [comment]
The key here is that all the blog posts inside this page are under /post and not under /blog/post which affects the way it is returned.

**Comment by nickscamara** [comment]
@poojaOgupta Just merged. Should be up in around ~10 minutes once its deployed. It should be fixed. The only different thing is that you should now make the request to `https://synctera.com/` and include `post/` and `blog/` subpahts as follows and pass the `ignoreSitemap` flag.

```{
    "url":"https://synctera.com/",
    "crawlerOptions": {
        "ignoreSitemap": true,
        "includes":["post/*","blog/*"]
    }
}
```
