### ISSUE TITLE
[Feat] Return whole url in crawl endpoint with returnUrlsOnly = true

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#259]
**Problem Description**
Often, a user wants to use the URLs returned in the crawl endpoint later for scraping.

However, currently, the URLs returned are relative, meaning that the user has to write some code to append the relative URL to the base URL. This isn't the end of the world, but it would be easier if the API just returned both. 

**Proposed Feature**
Return a "fullUrl" parameter with the whole URL returned as well as the relative URL

**Alternatives Considered**
The user can do this on their end. Consider this a nice to have for less technically savvy users.

thanks for the suggestion @iNicole5

**Comment by nickscamara** [comment]
Could you provide a url example of when this is happening? I tested on a couple websites and it is giving me back the full urls. 

<img width="834" alt="Screenshot 2024-06-10 at 4 52 40 PM" src="https://github.com/mendableai/firecrawl/assets/20311743/a148a2fb-c464-4f42-9b95-209df22582e9">
Coudl

**Comment by iNicole5** [comment]
Yea. One for example is this website: https://recruiting.paylocity.com/recruiting/jobs/All/d4447541-be32-4a64-81e4-fa735e6e2ec4/Icon-Vehicle-Dynamics-LLC

this is how it returns the URL: 
<img width="623" alt="Screenshot 2024-06-10 at 5 57 43 PM" src="https://github.com/mendableai/firecrawl/assets/40499551/a2601b7d-7b27-48fc-9f57-86614ebc1ada">

**Comment by rafaelsideguide** [comment]
Just tested here. So I think this happening for LLM Extractions: [example](https://www.firecrawl.dev/playground?url=https%3A%2F%2Frecruiting.paylocity.com%2Frecruiting%2Fjobs%2FAll%2Fd4447541-be32-4a64-81e4-fa735e6e2ec4%2FIcon-Vehicle-Dynamics-LLC&limit=10&excludes=&includes=&mode=llm-extract&generateImgAltText=false&onlyMainContent=false&fetchPageContent=true&extractionSchema=%7B%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22job%22%3A%7B%22type%22%3A%22array%22%2C%22items%22%3A%7B%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22company_name%22%3A%7B%22type%22%3A%22string%22%7D%2C%22job_title%22%3A%7B%22type%22%3A%22string%22%7D%2C%22job_location%22%3A%7B%22type%22%3A%22string%22%7D%2C%22salary%22%3A%7B%22type%22%3A%22string%22%7D%2C%22url%22%3A%7B%22type%22%3A%22string%22%7D%7D%7D%2C%22properties%22%3A%7B%7D%7D%7D%7D&extractionPrompt=Based+on+the+information+on+the+page%2C+extract+the+information+from+the+schema.+&maxDepth=&returnOnlyUrls=true&includeHtml=false&fastMode=false)

![Captura de Tela 2024-06-11 às 11 40 57](https://github.com/mendableai/firecrawl/assets/150964962/9d6b6f9c-07ee-4182-a8b5-053f2741be6a)

**Comment by iNicole5** [comment]
In my code I am not using LLM Extractions. But even so, when using the Firecrawl playground with the Crawl option. It does to return the 3 job urls that are posted. It gives me one URL and it is not the correct URL I am looking for.  [Example:](https://www.firecrawl.dev/playground?url=https%3A%2F%2Frecruiting.paylocity.com%2Frecruiting%2Fjobs%2FAll%2Fd4447541-be32-4a64-81e4-fa735e6e2ec4%2FIcon-Vehicle-Dynamics-LLC&limit=10&excludes=&includes=&mode=crawl&generateImgAltText=false&onlyMainContent=false&fetchPageContent=true&extractionSchema=%7B%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22job%22%3A%7B%22type%22%3A%22array%22%2C%22items%22%3A%7B%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22company_name%22%3A%7B%22type%22%3A%22string%22%7D%2C%22job_title%22%3A%7B%22type%22%3A%22string%22%7D%2C%22job_location%22%3A%7B%22type%22%3A%22string%22%7D%2C%22salary%22%3A%7B%22type%22%3A%22string%22%7D%2C%22url%22%3A%7B%22type%22%3A%22string%22%7D%7D%7D%2C%22properties%22%3A%7B%7D%7D%7D%7D&extractionPrompt=Based+on+the+information+on+the+page%2C+extract+the+information+from+the+schema.+&maxDepth=&returnOnlyUrls=true&includeHtml=false&fastMode=false)
<img width="1176" alt="Screenshot 2024-06-11 at 8 05 02 AM" src="https://github.com/mendableai/firecrawl/assets/40499551/8a17dc0a-f6bf-4e37-8951-bfbd2b3a2b4b">

**Comment by rafaelsideguide** [comment]
Hey @iNicole5!

It looks like the issue was that our crawler couldn't retrieve URLs that weren't direct "children" of the original URL. For example, from your starting URL `https://recruiting.paylocity.com/recruiting/jobs/All/d4447541-be32-4a64-81e4-fa735e6e2ec4/Icon-Vehicle-Dynamics-LLC`, links like `https://recruiting.paylocity.com/Recruiting/Jobs/Details/2496297` (that were present inside this page) weren't picked up because they don't follow directly from the original path.

To fix this, I've introduced a new feature called "allowBackwardCrawling" in PR #269. This feature enables the crawler to navigate backwards and retrieve all URLs.
 
 You can check this option on [playground](https://www.firecrawl.dev/playground):
<img width="1146" alt="Captura de Tela 2024-06-12 às 13 45 22" src="https://github.com/mendableai/firecrawl/assets/150964962/48edea8e-967e-49fe-84a0-560aa6b0aa9b">

Please give it a try and let us know how it works for you!

**Comment by iNicole5** [comment]
Thank you so much! @rafaelsideguide! It works perfect in my code! Thank you @rafaelsideguide  and @calebpeffer for your time! I appreciate it so much!

**Comment by rafaelsideguide** [comment]
@iNicole5 good to know it worked! I'm closing this issue.
