### ISSUE TITLE
[BUG][SELF-HOST] Crawl requests generate Supabase error.

### ISSUE THREAD

**Issue by mattjoyce** [mendableai/firecrawl#261]
On a self-host system, using latest main branch (10/June/2024).
Make requ4est for crawl via Python SDK.
The following error is show in Docker API-1 console.

> api-1                 | Attempted to access Supabase client when it's not configured.
> api-1                 | Error logging crawl job:
> api-1                 |  Error: Supabase client is not configured.
> api-1                 |     at Proxy.<anonymous> (/app/dist/src/services/supabase.js:38:23)
> api-1                 |     at logCrawl (/app/dist/src/services/logging/crawl_log.js:9:14)
> api-1                 |     at crawlController (/app/dist/src/controllers/crawl.js:87:40)
> api-1                 |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

I think it is caused by recent changes to **apps\api\src\services\webhook.ts**, specifically an attempt to get the webhook url from supabase.

If I'm right then I think there are a few options :
1. Simply test for USE_DB_AUTHENTICATION as well, if it's false - no webhook
2. Implement a new env SELF_HOSTED and use that to skip various stuff
3. Bake Superbase in to the self-host Docker setup  (have not got this going yet)

I think #1 is the quickest workaround, but architecturally it would be nice to have local drop in alternatives for all the non-local services.

**Comment by mattjoyce** [comment]
I have USE_DB_AUTHENTICATION=FALSE

**Comment by nickscamara** [comment]
Fixing that rnow!

**Comment by nickscamara** [comment]
Just pushed your first suggestion @mattjoyce I think that's the one that makes the most sense right now.

**Comment by nagendrakumar02** [comment]
Should I set SELF_HOSTED_WEBHOOK_URL = localhost:3002 to get rid of this error?
