### ISSUE TITLE
Used to extract structured data from scraped pages，How to customize the extractionScheme structure?

### ISSUE THREAD

**Issue by shenyugub** [mendableai/firecrawl#270]
curl -X POST https://api.firecrawl.dev/v0/scrape \
    -H 'Content-Type: application/json' \
    -H 'Authorization: Bearer YOUR_API_KEY' \
    -d '{
      "url": "https://www.mendable.ai/",
      "extractorOptions": {
        "mode": "llm-extraction",
        "extractionPrompt": "Based on the information on the page, extract the information from the schema. ",
        "extractionSchema": {
          "type": "object",
          "properties": {
            "company_mission": {
                      "type": "string"
            },
            "supports_sso": {
                      "type": "boolean"
            },
            "is_open_source": {
                      "type": "boolean"
            },
            "is_in_yc": {
                      "type": "boolean"
            }
          },
          "required": [
            "company_mission",
            "supports_sso",
            "is_open_source",
            "is_in_yc"
          ]
        }
      }
    }'

This is the data I tested. Can properties be customized? Or can we only retrieve these fields?

**Comment by rafaelsideguide** [comment]
@shenyugub you can use any json schema you want. If you prefer, you can create your json schema using our editor at [playground](https://www.firecrawl.dev/playground). Just select *LLM Extract* and you will see the editor in the "extraction schema" section.

**Comment by rafaelsideguide** [comment]
@shenyugub hey! Have you tested with other json schemas? Let me know if it worked!

**Comment by shenyugub** [comment]
> @shenyugub hey! Have you tested with other json schemas? Let me know if it worked!

I have a new question.

This is my test case, just the default example:
curl -X POST https://api.firecrawl.dev/v0/scrape \
    -H 'Content-Type: application/json' \
    -H 'Authorization: Bearer xxx' \
    -d '{
      "url": "https://mendable.ai/",
      "extractorOptions": {
        "mode": "llm-extraction",
        "extractionPrompt": "Based on the information on the page, extract the information from the schema. ",
        "extractionSchema": {
          "type": "object",
          "properties": {
            "company_mission": {
            	"type": "string"
            },
            "supports_sso": {
				"type": "boolean"
            },
            "is_open_source": {
            	"type": "boolean"
            },
            "is_in_yc": {
				"type": "boolean"
            }
          },
          "required": [
            "company_mission",
            "supports_sso",
            "is_open_source",
            "is_in_yc"
          ]
        }
      }
    }'

This is the response: 

{
    "success": true,
    "data": {
      "content": "Raw Content",
      "metadata": {
        "title": "Mendable",
        "description": "Mendable allows you to easily build AI chat applications. Ingest, customize, then deploy with one line of code anywhere you want. Brought to you by SideGuide",
        "robots": "follow, index",
        "ogTitle": "Mendable",
        "ogDescription": "Mendable allows you to easily build AI chat applications. Ingest, customize, then deploy with one line of code anywhere you want. Brought to you by SideGuide",
        "ogUrl": "https://mendable.ai/",
        "ogImage": "https://mendable.ai/mendable_new_og1.png",
        "ogLocaleAlternate": [],
        "ogSiteName": "Mendable",
        "sourceURL": "https://mendable.ai/"
      },
      "llm_extraction": {
        "company_mission": "Train a secure AI on your technical resources that answers customer and employee questions so your team doesn't have to",
        "supports_sso": true,
        "is_open_source": false,
        "is_in_yc": true
      }
    }
}

This is a screenshot of the 'https://mendable.ai/'
![image](https://github.com/mendableai/firecrawl/assets/38171999/21e8e774-b45f-44ed-95e9-73b29075aa0d)

This is my question: The field company_mission in llm_extraction，How is it related to the sentence in the page screenshot?

**Comment by shenyugub** [comment]
![image](https://github.com/mendableai/firecrawl/assets/38171999/54fdd758-2bef-44e9-adb1-ddd9023c08e1)
If I add a field, How do I associate this field with the data on the page?

**Comment by rafaelsideguide** [comment]
Closing this.
