### ISSUE TITLE
Self-hosting Firecrawl error

### ISSUE THREAD

**Issue by shenyugub** [mendableai/firecrawl#279]
Self-hosting Firecrawl error，why are errors reported when accessing port 3002
![1](https://github.com/mendableai/firecrawl/assets/38171999/c11e3643-4632-4601-821f-196e1a774bc8)
![2](https://github.com/mendableai/firecrawl/assets/38171999/6d72d67e-c8de-4b11-89e2-acb668d3e995)
![3](https://github.com/mendableai/firecrawl/assets/38171999/204a67df-2d56-4fe4-b984-e01c9b52d8dc)

**Comment by rafaelsideguide** [comment]
Hey @shenyugub, from the screenshots you attached, it looks like the system is working fine! Could you send us the error you're seeing?

**Comment by shenyugub** [comment]
> Hey @shenyugub, from the screenshots you attached, it looks like the system is working fine! Could you send us the error you're seeing?

Docker container and Service are running normally，but port 3002 show "Hello World"
![3](https://github.com/mendableai/firecrawl/assets/38171999/e4b80a91-7d3e-49b6-88f0-71ecb9a0c248)

**Comment by albertpurnama** [comment]
I think that's how it's supposed to be @shenyugub.

If you want to see the list of queues you should run go to `/admin/@/queues`.

If you're expecting a dashboard like www.firecrawl.dev you probably need to spin up the `www` app

**Comment by shenyugub** [comment]
> I think that's how it's supposed to be @shenyugub.
> 
> If you want to see the list of queues you should run go to `/admin/@/queues`.
> 
> If you're expecting a dashboard like [www.firecrawl.dev](http://www.firecrawl.dev) you probably need to spin up the `www` app

ok, thanks.

I have another question: if Self-hosting is successful, 'curl -X POST https://api.firecrawl.dev/v0/crawl' Can I change it to my address?

**Comment by shenyugub** [comment]
> I think that's how it's supposed to be @shenyugub.
> 
> If you want to see the list of queues you should run go to `/admin/@/queues`.
> 
> If you're expecting a dashboard like [www.firecrawl.dev](http://www.firecrawl.dev) you probably need to spin up the `www` app

ok, thanks
