### ISSUE TITLE
[BUG] Issue with cookies and navigation/footer with main content only.

### ISSUE THREAD

**Issue by AndyMik90** [mendableai/firecrawl#284]
**Describe the Bug**
Using main content function, brings in main menu (navigation elements), footer and cookie popup.

**To Reproduce**
Steps to reproduce the issue:
1. Set settings to scrape only main content
2. Scrape any page on https://Valma.ai

**Expected Behavior**
No navigation, footer or cookie to be scraped

**Screenshots**
![CleanShot 2024-06-14 at 23 02 06@2x](https://github.com/mendableai/firecrawl/assets/119136210/4c4276d1-6c20-4333-a548-3ac06a6abb2e)
![CleanShot 2024-06-14 at 23 03 39@2x](https://github.com/mendableai/firecrawl/assets/119136210/07ff8937-713f-4d86-ba8c-464aa05fce0b)
![CleanShot 2024-06-14 at 23 03 59@2x](https://github.com/mendableai/firecrawl/assets/119136210/86aef727-6ef4-43b2-8ef9-b1df555bbe40)

**Environment (please complete the following information):**
Both locally and on Firecrawl playground

**Additional Context**
It could be because this site is in Norwegian, but since it's an elementor website, the class names are in English, and the same goes for the cookie popup.

**Comment by nickscamara** [comment]
Thanks @AndyMik90! Looking into it. In the meantime to get around it you can pass your own exclude tags options with the `pageOptions.removeTags` option.

It accept tags, classes and ids to be removed from the page. Use comma separated values. Example: 'script, .ad, #footer'`

**Comment by AndyMik90** [comment]
> Thanks @AndyMik90! Looking into it. In the meantime to get around it you can pass your own exclude tags options with the `pageOptions.removeTags` option.
> 
> It accept tags, classes and ids to be removed from the page. Use comma separated values. Example: 'script, .ad, #footer'`

Thanks @nickscamara 

I will use the removeTags for now, I like how Firecrawl gives us more of the information, but there is a balance. We used Jina Reader it manages to remove the header, footer and cookiepopup, but it's a bit to harsh as it removes more of the main content: https://r.jina.ai/https://valma.ai

**Comment by nickscamara** [comment]
Sounds good yes @AndyMik90! We try to error on the side of not removing most things as they can be useful to the LLM. Will leave this issue open for now.

**Comment by AndyMik90** [comment]
> Sounds good yes @AndyMik90! We try to error on the side of not removing most things as they can be useful to the LLM. Will leave this issue open for now.

Does the removeTags option support regex? we are trying to add some common classes for header/footer/cookies in a broader fashion.

**Comment by AndyMik90** [comment]
@nickscamara, after testing some with removeTags, I noticed it's not robust enough.

I suggest implementing regex so at least we can remove tags that have the words "header," "footer," menu", "nav," "privacy" in the IDs

**Comment by nickscamara** [comment]
Hey @AndyMik90, thanks for the feedback, that makes sense. I am opening an issue for it, also free to to contribute if you'd like :)

**Comment by nickscamara** [comment]
#295 :)

**Comment by rafaelsideguide** [comment]
Hey @AndyMik90! Can I close this issue?

**Comment by AndyMik90** [comment]
> Hey @AndyMik90! Can I close this issue?

Yes we can close it, I actually saw a very interesting approach  when looking trough the code, that would make the scraping and parser very robust. I'll talk to Caleb about it on a meeting tomorrow.
