### ISSUE TITLE
[BUG] Issue crawling swift documentation

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#286]
Issue scraping the swift documentation:

Bug described by user on the /crawl endpoint

_Trying to scrape the documentation for Swift UI https://developer.apple.com/documentation/swiftui/ but it keeps stopping. It only does two pages, even with limit set to 50 and Include Only Paths=/documentation/swiftui/*

It got
https://developer.apple.c...swiftui/view-fundamentals
https://developer.apple.c...ntation/swiftui/clipboard_

**Comment by calebpeffer** [comment]
Notify @ gregschwartz when fixed

**Comment by snippet** [comment]
This issue was fixed by running the #325 service as a `PLAYWRIGHT_MICROSERVICE_URL`.
