### ISSUE TITLE
[Self-Host Question] Intense CPU Usage

### ISSUE THREAD

**Issue by albertpurnama** [mendableai/firecrawl#287]
<img width="613" alt="Screenshot 2024-06-14 at 5 57 17 PM" src="https://github.com/mendableai/firecrawl/assets/14824254/eb2e3946-49f6-4b55-9756-6390f5f5aa69">

The screenshot above is showing intense CPU usage on smallest (1vCPU 512MB resource) App Platform instance in DigitalOcean while in Idle state (no request coming in). Is this expected? Logs doesn't show anything suspicious.

What infra do you guys use to host this and what's the minimum required resource?

**Comment by nickscamara** [comment]
Hey @albertpurnama , I believe you might need at least 2vCPU with at least 2-4GB ram. We use fly.io for our deployments.

**Comment by nickscamara** [comment]
I just checked our instance and in idle it does use around ~450mb on idle. Probably because of the cluster setup we have. On line 16 in `api/index.ts` we make sure to use all CPUs available. Feel free to modify that to fit your needs and see if it helps.

```
const numCPUs = process.env.ENV === "local" ? 2 : os.cpus().length;
```

**Comment by albertpurnama** [comment]
Thanks!
