### ISSUE TITLE
{error: unauthorized} when running firecrawl locally

### ISSUE THREAD

**Issue by NeevJewalkar** [mendableai/firecrawl#292]
I have downloaded the repo, and run the scripts in /app/api (after reading CONTRIBUTING.md)
I am able to run the server, and the /test endpoint works. 
The problem is with /crawl endpoint:
```
$ curl -X POST http://localhost:3002/v0/crawl \                            
    -H 'Content-Type: application/json' \
    -d '{
      "url": "https://example.com"
    }'

$ {"error":"Unauthorized"}%                                                                                                                                                                    
```

No helpful logs in the shell running pnpm run start and pnpm run workers either.

**Comment by rafaelsideguide** [comment]
hey @NeevJewalkar have you changes the .env for `USE_DB_AUTHENTICATION=false`? There's a `/SELF_HOST.md` guide on the root of the project that can help you.

**Comment by NeevJewalkar** [comment]
ahah! yes it works, thank you!
