### ISSUE TITLE
[Feat] Support regex in remove tags

### ISSUE THREAD

**Issue by nickscamara** [mendableai/firecrawl#295]
Would be great to support regex in the `pageOptions.removeTags` attribute.

**Comment by nickscamara** [comment]
Suggested by AndyMik90

**Comment by AndyMik90** [comment]
@nickscamara PR ready: https://github.com/mendableai/firecrawl/pull/297

**Comment by rafaelsideguide** [comment]
Closing this as #297 has been merged into the `main`
