### ISSUE TITLE
[Feat] Add Anthropic Claude-3 Haiku as alternative to GPT-4 Vision (same quality, cheaper)

### ISSUE THREAD

**Issue by oliviermills** [mendableai/firecrawl#3]
Consider adding haiku or replacing with haiku for image in [utils/gptVision.ts](https://github.com/mendableai/firecrawl/blob/main/apps/api/src/scraper/WebScraper/utils/gptVision.ts)
The same prompt will work well.

Also you should probably shift to the now `gpt-4-turbo` which [recommended](https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4) instead of the vision model

**Comment by calebpeffer** [comment]
Great Points! We already use gpt-4-turbo, but haiku will be a great alternative. @rafaelsideguide

**Comment by rafaelsideguide** [comment]
Hey @oliviermills I just implemented it using `claude-3-opus-20240229`
