### ISSUE TITLE
feat: excludes to be used to exclude file types like pdfs

### ISSUE THREAD

**Issue by nickscamara** [mendableai/firecrawl#309]
Ability to use the `excludes` param to exclude file types in urls:
```
"crawlerOptions": {
    "excludes":["*.pdf"],
    "returnOnlyUrls": False,
    "maxDepth": 3,
    "mode": "default",
    "limit": 10
},
```
Suggested by @kaleb_claimgem_14851 on Discord

**Comment by rafaelsideguide** [comment]
Duplicated. Closing this in favor of the more detailed one https://github.com/mendableai/firecrawl/issues/465
