### ISSUE TITLE
[BUG]Why “Error: Missing lock for job 0677c04f-78b2-4917-ae53-e701a5611b3c finished” happened？

### ISSUE THREAD

**Issue by Longleaves** [mendableai/firecrawl#320]
When I run locally, I found an error on UI(http://0.0.0.0:3002/admin/@/queues), the error is:
![图片](https://github.com/mendableai/firecrawl/assets/58903935/542166b2-a07f-4215-8081-1451f7a9599d)
And my pnpm showed:
Error: Error: All scraping methods failed for URL
Error sending webhook for team ID: undefined Failed to parse URL from undefined
![图片](https://github.com/mendableai/firecrawl/assets/58903935/145f9975-7779-4248-9e20-55f08ebcefd4)
![图片](https://github.com/mendableai/firecrawl/assets/58903935/b61095c5-8f26-422a-99ab-1351d1aad337)

Please help me, thanks a lot!

**Comment by rafaelsideguide** [comment]
@Longleaves can you share the url you're trying to scrape?

**Comment by Longleaves** [comment]
> @Longleaves can you share the url you're trying to scrape?

the url is your example:
"url": "https://mendable.ai"

these showed in the error column:
![图片](https://github.com/mendableai/firecrawl/assets/58903935/100c1c9e-9773-47c9-bdf0-2862cfb0ba2a)

But I found that the return result showed in "data" column:
{
  "jobData": {
    "url": "https://mendable.ai",
    "mode": "crawl",
    "crawlerOptions": {
      "allowBackwardCrawling": false
    },
    "pageOptions": {
      "onlyMainContent": false,
      "includeHtml": false,
      "removeTags": [],
      "parsePDF": true
    },
    "origin": "api"
  },
  "returnValue": [
    {
      "content": "\n\nIntroducing [Firecrawl](https://firecrawl.dev/?ref=mendable+banner)\n 🔥 - Turn entire websites into LLM-ready markdown or structured data\n\n[![Mendable logo](https://www.mendable.ai/Frame%20566%20(2)Mendable](/)\n\n*   Getting started\n*   Use Cases\n*   [Docs](https://docs.mendable.ai)\n    \n*   [Pricing](/pricing)\n    \n*   [Blog](/blog)\n    \n\nOpen main menu\n\n[Sign In](/signin)\n[Get Started](/signup)\n\n![](https://www.mendable.ai/fullbgdsm.png)\n\n[$ npm i @mendable/search](https://docs.mendable.ai)\n\nJust in time answers  \nfor Sales and Support\n============================================\n\nTrain a secure AI on your technical resources that answers customer and employee questions so your team doesn't have to\n\nGet Started\n\nTalk to Us\n\nBacked BY\n\n![Y Combinator Logo](https://www.mendable.ai/yc.svg)Combinator\n\ninvisible\n\nAssistant\n\nHi, how can I help you?\n\nAsk\n\nLoading...\n\n![Mendable loading placeholder image](https://www.mendable.ai/heroloading.png)\n\nFrom small startups to Fortune 500\n\nTrusted by top companies\n------------------------\n\n![Snapchat](https://www.mendable.ai/customers/snapchat2.svg)\n\n![MongoDB](https://www.mendable.ai/customers/mongo.svg)\n\n![Langchain](https://www.mendable.ai/customers/coinbase.svg)\n\n![Worldline](https://www.mendable.ai/customers/world.svg)\n\n![Nylas](https://www.mendable.ai/customers/nylass.svg)\n\n![Spectrocloud](https://www.mendable.ai/customers/spectro.svg)\n\n![Merge](https://www.mendable.ai/customers/merge.svg)\n\n![0x](https://www.mendable.ai/customers/zeroxx.svg)\n\n![Tecton.ai](https://www.mendable.ai/customers/tecton.svg)\n\n![Llama Index](https://www.mendable.ai/customers/llamaindex.png)\n\nDeploy a knowledgable technical AI anywhere\n\nUse Mendable for\n----------------\n\n[Docs & Knowledge Base](/usecases/documentation)\n\n-------------------------------------------------\n\nDecrease tickets & activation times with an AI assistant\n\n[Customer Success Enablement](/usecases/cs-enablement)\n\n-------------------------------------------------------\n\nUse a technical AI copilot to increase retention\n\n[Sales Enablement](/usecases/sales-enablement)\n\n-----------------------------------------------\n\nUse a technical AI copilot to build trust with prospects\n\n[Product Copilot](/usecases/productcopilot)\n\n--------------------------------------------\n\nSpeed up adoption with a technical assistant in your app\n\nSee how companies implement Mendable\n------------------------------------\n\n![](https://www.mendable.ai/langchain.png)\n\n[Langchain Docs](https://python.langchain.com)\n\n-----------------------------------------------\n\nOne of the most popular frameworks for developing AI applications\n\nhttps://python.langchain.com\n\n![](https://www.mendable.ai/0xlogo.png)\n\n[0x Docs](https://0x.org/docs)\n\n-------------------------------\n\n0x offers the core building blocks to create the most powerful Web3 apps\n\nhttps://0x.org/docs\n\n![](https://www.mendable.ai/zenlytics.png)\n\n[Zenlytics](https://docs.zenlytic.com)\n\n---------------------------------------\n\nSelf-serve analytics tool that helps you answer the deeper questions you have about your data\n\nhttps://docs.zenlytic.com\n\n![](https://www.mendable.ai/LlamaIndex.png)\n\n[Llama Index](http://gpt-index.readthedocs.io)\n\n-----------------------------------------------\n\nA central interface to connect your LLM’s with external data.\n\nhttp://gpt-index.readthedocs.io\n\n![](https://www.mendable.ai/spectrocloud-white.png)\n\n[Spectrocloud](https://docs.spectrocloud.com/)\n\n-----------------------------------------------\n\nK8s management uniquely built for scale. Manage the lifecycle of any type of cluster.\n\nhttps://docs.spectrocloud.com/\n\n![](https://www.mendable.ai/codegpt.png)\n\n[Code GPT](https://www.codegpt.co/)\n\n------------------------------------\n\nWith over 450,000 installs, CodeGPT brings AI inside your code editor.\n\nhttps://www.codegpt.co/\n\nAnd many more...\n\nFrom SSO to BYOK\n\nEnterprise-grade security\n--------------------
…………

Is this a normal mistake I can ignore?
And I wanna ask how can I get the crawl result directly?

**Comment by Longleaves** [comment]
I also found: "error": "No pages found" and the same errors showed in pnpm.

{
  "jobData": {
    "url": "https://www.baidu.com/",
    "mode": "crawl",
    "crawlerOptions": {
      "allowBackwardCrawling": false
    },
    "pageOptions": {
      "includeHtml": false,
      "onlyMainContent": true,
      "waitFor": 5000
    },
    "origin": "api"
  },
  "returnValue": {
    "success": true,
    "result": {
      "links": []
    },
    "error": "No pages found"
  }
}

![343095951-145f9975-7779-4248-9e20-55f08ebcefd4](https://github.com/mendableai/firecrawl/assets/58903935/f939b331-7157-4796-8c67-3e2cafcc30a0)
![343115458-b61095c5-8f26-422a-99ab-1351d1aad337](https://github.com/mendableai/firecrawl/assets/58903935/23467c75-b40d-41d9-863e-733838b1a94b)

**Comment by xingfanxia** [comment]
having some issue

**Comment by nickscamara** [comment]
ccing @rafaelsideguide

**Comment by rafaelsideguide** [comment]
@xingfanxia @Longleaves we were able to reproduce this error and we're fixing the `missing lock for job id` error in our next release. In the meantime, you can still fetch the results from your crawls using the crawl/status endpoint. Check out the docs [here](https://docs.firecrawl.dev/api-reference/endpoint/status) for how to use it.
