### ISSUE TITLE
How do I get the results returned by the crawler through jobid?

### ISSUE THREAD

**Issue by Longleaves** [mendableai/firecrawl#330]
I can only see the result via  http://localhost:3002/admin/undefined/queues/. How can I get the returnValue directly by curling some URL or doing something?
Thanks a lot if u answer me!

**Comment by rafaelsideguide** [comment]
Hey @Longleaves! For the details on how to retrieve the status of a completed crawl job, you should check out the status endpoint section in our documentation here: https://docs.firecrawl.dev/api-reference/endpoint/status. It has all the information you’ll need to access the content of the job.

**Comment by Longleaves** [comment]
> Hey @Longleaves! For the details on how to retrieve the status of a completed crawl job, you should check out the status endpoint section in our documentation here: https://docs.firecrawl.dev/api-reference/endpoint/status. It has all the information you’ll need to access the content of the job.

Hi @rafaelsideguide !
I cannot get the status of a complieted crawl job when I follow https://docs.firecrawl.dev/api-reference/endpoint/status
My command is: curl --request GET --url https://localhost:3002/v0/crawl/status/{114717d1-06cc-41a5-8a60-1fef97b1576d}
Error happened: curl: (35) OpenSSL/3.0.13: error:0A00010B:SSL routines::wrong version number
![图片](https://github.com/mendableai/firecrawl/assets/58903935/773267d4-ed07-4f8c-be45-c89a04a872e7)
By the way, What does "Authorization: Bearer <token>" mean when I'm running locally?

**Comment by rafaelsideguide** [comment]
@Longleaves Try without the brackets: https://localhost:3002/v0/crawl/status/114717d1-06cc-41a5-8a60-1fef97b1576d

The authorization doesn't matter if you're not using the database for authentication, so you can leave it empty or add something like `fc-123`.

**Comment by Longleaves** [comment]
> @Longleaves Try without the brackets: https://localhost:3002/v0/crawl/status/114717d1-06cc-41a5-8a60-1fef97b1576d
> 
> The authorization doesn't matter if you're not using the database for authentication, so you can leave it empty or add something like `fc-123`.

It doesn't work @rafaelsideguide :
![图片](https://github.com/mendableai/firecrawl/assets/58903935/b559515a-1db0-40df-94cc-e0199a519b46)

**Comment by Longleaves** [comment]
Hi, @rafaelsideguide 
I just used: curl --request GET --url https://localhost:3002/v0/crawl/status/114717d1-06cc-41a5-8a60-1fef97b1576d
Is it right? Errors showed: curl: (35) OpenSSL/3.0.13: error:0A00010B:SSL routines::wrong version number
Can u make it?
Thanks!

**Comment by rafaelsideguide** [comment]
oh you have to remove the "s" from https for local requests. The right value for path is: http://localhost:3002/v0/crawl/status/114717d1-06cc-41a5-8a60-1fef97b1576d

**Comment by Longleaves** [comment]
> oh you have to remove the "s" from https for local requests. The right value for path is: http://localhost:3002/v0/crawl/status/114717d1-06cc-41a5-8a60-1fef97b1576d

It works！Thank u so much!

**Comment by rafaelsideguide** [comment]
@Longleaves awesome! I'm closing this issue.
