### ISSUE TITLE
[Feat] (CONTRIBUTOR.md / docker-compose) Better onbording with docker

### ISSUE THREAD

**Issue by Sanix-Darker** [mendableai/firecrawl#358]
**Problem Description**
For me it was a little hard to have to start 3 terminals before having the whole stack up and running, we already have a docker compose, why not using it ?

**Proposed Feature**
I updated the contributor guide to add contribution using docker and live reloaded on file changes by attaching the volumes of `apps/api`

**Implementation Suggestions**
More details here : https://github.com/mendableai/firecrawl/pull/357

**Comment by Sanix-Darker** [comment]
Now, am wondering if "profiles" is not a better idea to separate dev/prod https://docs.docker.com/compose/profiles/ ... it looks a little cleaner but both solutions should work

**Comment by rafaelsideguide** [comment]
@Sanix-Darker I think we already solved this issue with the new docker compose. Please check [contributing guide](https://docs.firecrawl.dev/contributing/guide) and [self host guide](https://docs.firecrawl.dev/contributing/self-host).  I'm closing this for now, but feel free to reopen this issue if you think it makes sense.

**Comment by Sanix-Darker** [comment]
@rafaelsideguide , thanks for the reply, am closing the related draft PR too.
