### ISSUE TITLE
[BUG] Cant open the admin UI

### ISSUE THREAD

**Issue by wwwDESIGN-basti** [mendableai/firecrawl#401]
**Describe the Bug**
After a fresh Install (via Docker) on a Mac M1, there is no way to open the admin interface.

http://0.0.0.0:3002/admin/#/queues
<img width="461" alt="image" src="https://github.com/user-attachments/assets/d1789174-af2f-494d-8431-2de67251b1fe">

The USE_DB_AUTHENTICATION is on false.

How can i fix that?

**Comment by rafaelsideguide** [comment]
@wwwDESIGN-basti could you check the `BULL_AUTH_KEY` value in your `.env` file? This value is used to access the Bull UI. By default, the value is `@`, and the URL is `http://0.0.0.0:3002/admin/@/queues`.

**Comment by wwwDESIGN-basti** [comment]
thanks, that was the issue.
