### ISSUE TITLE
[BUG] Use seelf hosted firecrawl apiUrl in JS SDK ?

### ISSUE THREAD

**Issue by theodufort** [mendableai/firecrawl#407]
**Describe the Bug**
I am trying to use my self hosted firecrawl api server for the JS SDK.

**To Reproduce**
Steps to reproduce the issue:
1. Have a running firecrawl REST server
2. pass your local apiUrl variable.

**Expected Behavior**
POST request is sent to locally hosted firecrawl server.

I want to use my own self hosted firecrawl instance using the JS SDK:
`const crawler = new FirecrawlApp({
  apiUrl: "http://192.168.0.216:3112/v0/crawl",
  apiKey: null,
});`

but i get:
`20 |      */
21 |     constructor({ apiKey = null, apiUrl = null }) {
22 |         this.apiKey = apiKey || "";
23 |         this.apiUrl = apiUrl || "https://api.firecrawl.dev";
24 |         if (!this.apiKey) {
25 |             throw new Error("No API key provided");
                       ^
error: No API key provided`

**Comment by rafaelsideguide** [comment]
Closing for now. Feel free to reopen if you continue to experience this problem.
