### ISSUE TITLE
limits include filtered out paths

### ISSUE THREAD

**Issue by red545** [mendableai/firecrawl#41]
the crawl limit is applied before the paths are filtered out. 

**base url:** `test.com`
**limit:** `2`
**included links:** `["/pages/*"]`

links on test.com in order: 
```
[
"/home",
"/imprint",
"/about",
"pages/1",
"pages/2",
"pages/3"
]
```

**expected links to be crawled:** `["pages/1","pages/2"]`

**current links that are crawled:** `[]`

**Comment by nickscamara** [comment]
Thanks for spotting and fixing that! Will take a look at it soon :)

**Comment by rafaelsideguide** [comment]
I'm unable to reproduce the issue.

[Tested](https://www.firecrawl.dev/playground?url=mendable.ai&limit=2&excludes=&includes=%2Fblog%2F*&mode=crawl&generateImgAltText=false&onlyMainContent=false) with:
base url: `mendable.ai`
limit: `2`
included only paths: `/blog/*`
results: `[https://www.mendable.ai/blog/august2023update, https://www.mendable.ai/blog/building-copilots]`

@red545 can you send us a real example?

**Comment by red545** [comment]
@rafaelsideguide 

base url: `https://www.newimmobilien.at/sie-suchen-eine-immobilie `
limit: `5`
included only paths: `objektdetail/*`

results: anywhere from 0-2 results at any given time. 

but the issue might be even deeper. I am trying to scrape the following url: 
`https://www.newimmobilien.at/objektdetail/13521532?from=166590` which is resulting in `Page not Found`

while I can sometimes crawl the page. sadly this is not deterministic

**Comment by nickscamara** [comment]
I wonder if it has anything to do with the query params.

@rafaelsideguide

**Comment by calebpeffer** [comment]
I tried reproducing again, to no avail

<img width="488" alt="image" src="https://github.com/mendableai/firecrawl/assets/44934913/9c13095c-4223-416e-a132-7a3987b2a74b">

<img width="548" alt="image" src="https://github.com/mendableai/firecrawl/assets/44934913/e0bcd5c4-e1f4-490f-ac77-c50abf9faa91">

I checked the logs, and it's been working great since this morning. Maybe it's a concurrency issue?

**Comment by red545** [comment]
same for me. this seems to be fixed now
