### ISSUE TITLE
[BUG] Allow scraping of files (like PDFs) that are more than 10mb

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#413]
We just lost a customer because we weren't able to scrape a pdf on the tesla website. 

For pdf files, we have a limit of 10mb (right @rafaelsideguide, you mentioned this to me via slack) regarding this discussion https://github.com/mendableai/firecrawl/discussions/51#discussioncomment-9941986

If possible, we need to get around this limit so customers aren't left in the dark as to why a particular PDF wasn't processed

**Comment by nickscamara** [comment]
@calebpeffer let's wait on this for now, we have some other high priority that are affecting other customers. @rafaelsideguide feel free to do those first then, unblock this one.

**Comment by calebpeffer** [comment]
Hey, this issue is a customer priority and shouldn't be blocked.

**Comment by nickscamara** [comment]
@calebpeffer it is already on the v1 todos btw.

**Comment by nickscamara** [comment]
API doesn't support that right now.

**Comment by ollegreen** [comment]
nudge on this as this is an issue still. trying to extract >10MB PDFs (e.g [burberry annual report PDF example](https://www.burberryplc.com/content/dam/burberryplc/corporate/oar/oar-2024-2025/annual-report-2024-25.pdf)) 

bought the $99 plan to test before considering enterprise. So thought it would be worth highlighting, as this limitation will unfortunately make me move back to Tavily. 

if there's a solve for this: would love to hear it. 

Cheers

**Comment by teknium1** [comment]
Same here. Need 25+MB limit please..
