### ISSUE TITLE
[Feat] proxy for scraper

### ISSUE THREAD

**Issue by NiuBlibing** [mendableai/firecrawl#416]
**Problem Description**
In some network, google and others website are not directly accessable.

**Proposed Feature**
provide a proxy option for crawler google and other website.

**Comment by NiuBlibing** [comment]
I found a way to do it:
set `http_proxy` `https_proxy` and `no_proxy` 

[axios](https://axios-http.com/docs/req_config)

>   // `proxy` defines the hostname, port, and protocol of the proxy server.
>  // You can also define your proxy using the conventional `http_proxy` and
>  // `https_proxy` environment variables. If you are using environment variables
>  // for your proxy configuration, you can also define a `no_proxy` environment
>  // variable as a comma-separated list of domains that should not be proxied.
>  // Use `false` to disable proxies, ignoring environment variables.
>  // `auth` indicates that HTTP Basic auth should be used to connect to the proxy, and
>  // supplies credentials.
>  // This will set an `Proxy-Authorization` header, overwriting any existing
>  // `Proxy-Authorization` custom headers you have set using `headers`.
>  // If the proxy server uses HTTPS, then you must set the protocol to `https`.

**Comment by mohit-singh-pepper** [comment]
@NiuBlibing did you fork and change library code for this ? Although axios allows proxy adding it while calling firecrawl won't help. The proxy has to be added in firecrawl to google call.

**Comment by NiuBlibing** [comment]
> @NiuBlibing did you fork and change library code for this ? Although axios allows proxy adding it while calling firecrawl won't help. The proxy has to be added in firecrawl to google call.

Thank you, I'll try the latest version.
