### ISSUE TITLE
Docs: image with python snippet

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#43]
<img width="554" alt="image" src="https://github.com/mendableai/firecrawl/assets/44934913/0965fd9d-fb4a-4362-878c-b59fe8871e55">

**Comment by nickscamara** [comment]
Where is the wrong snippet located? Couldn't find it.

**Comment by nickscamara** [comment]
Nvmd, was on the playground. Fixed.

Closing this...
