### ISSUE TITLE
[BUG] /Scrape on this link is taking 20s. Why? 

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#434]
https://dlp.dubai.gov.ae/en/Pages/OfficialGazette.aspx

@mogery

**Comment by nickscamara** [comment]
@rafaelsideguide was this the one you fixed?

**Comment by rafaelsideguide** [comment]
@nickscamara no, I haven't checked this one.

**Comment by mogery** [comment]
Only takes 1.8s now. Closing
