### ISSUE TITLE
[BUG] ClientSide Application error on some pages in playground on mendable.ai

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#439]
Getting Application error: a client-side exception has occurred when I run mendable.ai on the playground. Unfortunately, this was visible in a client demo earlier today (although I tried to distract from it) 

![image](https://github.com/user-attachments/assets/eb3a7e75-0cce-493d-a98e-632f114cfed1) 

Not sure what is going on

**Comment by nickscamara** [comment]
I think we fixed this it seems.

**Comment by antonioalegria** [comment]
I have the same error for a few sites, using the API. Is this the same issue?

**Comment by nickscamara** [comment]
@antonioalegria can you share the websites you had this on?

**Comment by antonioalegria** [comment]
https://ecologi.com is an example

**Comment by nickscamara** [comment]
Thank you @antonioalegria! @tomkosm is looking into it

**Comment by tomkosm** [comment]
Hey @antonioalegria ,
Application error has been fixed. I wasn't able to reproduce the issue with https://amplemarket.com/ , if this issue persists please open a new issue so we can have a look. Closing this as the Application error has now been fixed.

**Comment by antonioalegria** [comment]
Thanks will take a look.
