### ISSUE TITLE
I notice in the documentation that it's not quite ready for full self-hosting deployment. But what happens if I want to deploy with an offline server?[Feat]

### ISSUE THREAD

**Issue by 2842902295** [mendableai/firecrawl#448]
**Problem Description**
Describe the issue you're experiencing that has prompted this feature request. For example, "I find it difficult when..."

**Proposed Feature**
Provide a clear and concise description of the feature you would like implemented.

**Alternatives Considered**
Discuss any alternative solutions or features you've considered. Why were these alternatives not suitable?

**Implementation Suggestions**
If you have ideas on how the feature could be implemented, share them here. This could include technical details, API changes, or interaction mechanisms.

**Use Case**
Explain how this feature would be used and what benefits it would bring. Include specific examples to illustrate how this would improve functionality or user experience.

**Additional Context**
Add any other context such as comparisons with similar features in other products, or links to prototypes or mockups.

**Comment by nickscamara** [comment]
Hi, you can easily self host firecrawl. The only thing that is not currently ready is the database side of things. You can set USE_DB_AUTHENTICATION=false and deploy your offline server without the auth layer.

**Comment by furquanh** [comment]
> Hi, you can easily self host firecrawl. The only thing that is not currently ready is the database side of things. You can set USE_DB_AUTHENTICATION=false and deploy your offline server without the auth layer.

Hi Nick,

Is the scraper name fire-engine proprietary to firecrawl.dev or is it open source aswell?

**Comment by nickscamara** [comment]
Hey @furquanh, Currently fire-engine is not available for the self hosted version. We are still figuring out the offer there and it is not (yet) open-source.

**Comment by nickscamara** [comment]
@2842902295 We just pushed better guides on self-hosting. Hope that helps!
