### ISSUE TITLE
Readiness and Liveness Probes [Feat]

### ISSUE THREAD

**Issue by JakobStadlhuber** [mendableai/firecrawl#451]
**Problem Description**
There are no Readiness and Liveness Probes for Health Monitoring or Self Healing processes

**Proposed Feature**
Readiness and Liveness HTTP Routes for every service

**Alternatives Considered**
none

**Implementation Suggestions**
see proposed

**Use Case**
Kubernetes Probes, Status/Health Pages

**Additional Context**
This can be extended with Redis checks or deep health checks

**Comment by JakobStadlhuber** [comment]
If no one has time, I can also have a look into it.

**Comment by JakobStadlhuber** [comment]
#457

**Comment by nickscamara** [comment]
That's great @JakobStadlhuber! We will take a look at it soon!

**Comment by nickscamara** [comment]
Got merged! Closing this :)
