### ISSUE TITLE
An error occurred: Unexpected error during scrape URL: Unexpected error during scrape URL: Status code 401. Unauthorized: Invalid toke[BUG]

### ISSUE THREAD

**Issue by Thaslim42** [mendableai/firecrawl#452]
while using fire crawl api key it is showing this error

**Comment by nickscamara** [comment]
Hey @Thaslim42 are you using the cloud service or self hosting?

**Comment by uestchjw** [comment]
Me too

**Comment by uestchjw** [comment]
I think I have a misunderstanding of the "api key". At first, I use the Gemini API Key in 
`app = FirecrawlApp(api_key="YOUR_API_KEY")`
and return 
`requests.exceptions.HTTPError: Unexpected error during scrape URL: Status code 401. Unauthorized: Invalid token`.
**However, I should use the API Key from the FireCrawl playground and there are no mistakes anymore.**
