### ISSUE TITLE
Locally hosted firecrawl stuck when called from dify

### ISSUE THREAD

**Issue by kouyakamada** [mendableai/firecrawl#464]
I want to call firecrawl hosted on the company network from a dify hosted on the same network.
It registers to dify with no problem, but when I run the crawl, it gets stuck with no response from firecrawl.
Checking the ``docker compose logs`` seems to show an error.
What is the cause of this?

Expected Behavior:
Can call firecrawl from a dify hosted on the company network.

Environment :
Based on dokcer compose in repository.

![image](https://github.com/user-attachments/assets/174d5f1c-b336-47b3-9e02-6a40ca4d31a7)

**docker compose logs** 
```bash
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
api-1                 | [2024-07-26T04:18:38.474Z]INFO - Number of CPUs: 64 available
api-1                 | [2024-07-26T04:18:38.475Z]INFO - Worker 201 listening on port 3002
api-1                 | [2024-07-26T04:18:38.475Z]INFO - For the Queue UI, open: http://0.0.0.0:3002/admin/@/queues
api-1                 | [2024-07-26T04:18:38.477Z]INFO - Connected to Redis Session Rate Limit Store!
api-1                 | [2024-07-26T04:18:38.482Z]INFO - Web scraper queue created
api-1                 | [2024-07-26T04:18:38.485Z]INFO - Worker 66 started
api-1                 | [2024-07-26T04:18:38.488Z]INFO - Number of CPUs: 64 available
api-1                 | [2024-07-26T04:18:38.495Z]INFO - Web scraper queue created
api-1                 | [2024-07-26T04:18:38.499Z]INFO - Worker 171 started
api-1                 | [2024-07-26T04:18:38.499Z]INFO - Worker 66 listening on port 3002
api-1                 | [2024-07-26T04:18:38.500Z]INFO - For the Queue UI, open: http://0.0.0.0:3002/admin/@/queues
api-1                 | [2024-07-26T04:18:38.502Z]INFO - Connected to Redis Session Rate Limit Store!
api-1                 | [2024-07-26T04:18:38.513Z]INFO - Worker 171 listening on port 3002
api-1                 | [2024-07-26T04:18:38.513Z]INFO - For the Queue UI, open: http://0.0.0.0:3002/admin/@/queues
api-1                 | [2024-07-26T04:18:38.513Z]INFO - Number of CPUs: 64 available
api-1                 | [2024-07-26T04:18:38.516Z]INFO - Connected to Redis Session Rate Limit Store!
api-1                 | [2024-07-26T04:18:38.521Z]INFO - Web scraper queue created
api-1                 | [2024-07-26T04:18:38.525Z]INFO - Worker 391 started
api-1                 | [2024-07-26T04:18:38.542Z]INFO - Worker 391 listening on port 3002
api-1                 | [2024-07-26T04:18:38.542Z]INFO - For the Queue UI, open: http://0.0.0.0:3002/admin/@/queues
api-1                 | [2024-07-26T04:18:38.545Z]INFO - Connected to Redis Session Rate Limit Store!
api-1                 | [2024-07-26T04:18:45.372Z]WARN - You're bypassing authentication
api-1                 | [2024-07-26T04:18:45.373Z]WARN - You're bypassing authentication
api-1                 | [2024-07-26T04:18:45.379Z]ERROR - Attempted to access Supabase client when it's not configured.
api-1                 | [2024-07-26T04:18:45.380Z]ERROR - Error inserting scrape event: Error: Supabase client is not configured.
api-1                 | [2024-07-26T04:18:45.471Z]ERROR - Attempted to access Supabase client when it's not configured.
api-1                 | [2024-07-26T04:18:45.471Z]ERROR - Error inserting scrape event: Error: Supabase client is not configured.
api-1                 | [2024-07-26T04:18:45.478Z]ERROR - Attempted to access Supabase client when it's not configured.
api-1                 | [2024-07-26T04:18:45.479Z]ERROR - Error inserting scrape event: Error: Supabase client is not configured.
api-1                 | [2024-07-26T04:18:45.487Z]ERROR - Attempted to access Supabase client when it's not configured.
api-1                 | [2024-07-26T04:18:45.487Z]ERROR - Error inserting scrape event: Error: Supabase client is not configured.
```

**Proxy settings added to dockerfile**
```dockerfile
ENV HTTPS_PROXY=http://xxx.xxx.xxx:3128
ENV HTTP_PROXY=http://xxx.xxx.xxx:3128
ENV https_proxy=http://xxx.xxx.xxx:3128
ENV http_proxy=http://xxx.xxx.xxx:3128
ENV NO_PROXY=127.0.0.1,localhost,redis,api,worker,playwright-service
ENV no_proxy=127.0.0.1,localhost,redis,api,worker,playwright-service

RUN npm -g config set proxy http://xxx.xxx.xxx:3128
RUN npm -g config set https-proxy http://xxx.xxx.xxx:3128
```

**Result of calling api from command line**
```bash
curl -X POST http://xx.xx.xx.xx:3002/v0/scrape -H 'Content-Type: application/json' -d '{"url":"https://www.firecrawl.dev/"}'
{"success":true,"error":"No page found","returnCode":200,"data":{"content":"","markdown":"","html":"","linksOnPage":[],"metadata":{"sourceURL":"https://www.firecrawl.dev/","pageStatusCode":400,"pageError":"Bad Request"}}}
```

**Comment by nickscamara** [comment]
@kouyakamada were you able to figure this out? We published a lot more improvements to our self hosting guide. Let us know if that helps.

**Comment by tak-s** [comment]
I also encountered an issue where crawling did not work well in a Proxy environment.

By modifying the area around axios.get() in `apps/api/src/scraper/WebScraper/scrapers/fetch.ts`, as shown below, I was able to resolve the issue.

```
// add module
import * as tunnel from 'tunnel';
```

```
try {
  //const response = await axios.get(url, {
  //  headers: {
  //    "Content-Type": "application/json",
  //  },
  //  timeout: universalTimeout,
  //  transformResponse: [(data) => data], // Prevent axios from parsing JSON automatically
  //});

  // Set proxy agent
  let agent;
  const httpProxy = process.env.HTTP_PROXY || null;
  const httpsProxy = process.env.HTTPS_PROXY || null;

  if (url.startsWith('https://') && httpsProxy) {
    const httpsProxyUrl = new URL(httpsProxy);
    agent = tunnel.httpsOverHttp({
      proxy: {
        host: httpsProxyUrl.hostname,
        port: parseInt(httpsProxyUrl.port, 10),
      },
    });
    Logger.info(`Using tunnel agent with HTTPS proxy: ${httpsProxy}`);
  } else if (url.startsWith('http://') && httpProxy) {
    const httpProxyUrl = new URL(httpProxy);
    agent = tunnel.httpOverHttp({
      proxy: {
        host: httpProxyUrl.hostname,
        port: parseInt(httpProxyUrl.port, 10),
      },
    });
    Logger.info(`Using tunnel agent with HTTP proxy: ${httpProxy}`);
  } else {
    Logger.info(`No proxy settings found or not required for the URL: ${url}. Proceeding without a proxy.`);
  }

  const response = await axios.get(url, {
    headers: {
      "Content-Type": "application/json",
    },
    timeout: universalTimeout,
    transformResponse: [(data) => data], // Prevent axios from parsing JSON automatically
    ...(agent ? { httpsAgent: agent, proxy: false } : {}), // set proxy agent
  });
```

Add the `tunnel` module to `apps/api/Dockerfile`

```
RUN pnpm install
RUN pnpm add tunnel    # add
RUN pnpm run build
```

Build with docker compose and start the container.

```
docker compose build && docker compose up -d
```

I hope this helps.

**Comment by artificialzjy** [comment]
想问下您，您是通过API Key将FireCrawl注册到Dify中的吗？如果是，您本地部署的FireCrawl是如何获取API Key的以及如何设置Authorization的？

**Comment by NuerSir** [comment]
@artificialzjy TEST_API_KEY

**Comment by kouyakamada** [comment]
@tak-s 
Sorry for the late reply.
Now able to crawl within our internal network and call it from dify!
Thank you!

**Comment by danialcheung** [comment]
> I also encountered an issue where crawling did not work well in a Proxy environment.
> 
> By modifying the area around axios.get() in `apps/api/src/scraper/WebScraper/scrapers/fetch.ts`, as shown below, I was able to resolve the issue.
> 
> ```
> // add module
> import * as tunnel from 'tunnel';
> ```
> 
> ```
> try {
>   //const response = await axios.get(url, {
>   //  headers: {
>   //    "Content-Type": "application/json",
>   //  },
>   //  timeout: universalTimeout,
>   //  transformResponse: [(data) => data], // Prevent axios from parsing JSON automatically
>   //});
> 
>   // Set proxy agent
>   let agent;
>   const httpProxy = process.env.HTTP_PROXY || null;
>   const httpsProxy = process.env.HTTPS_PROXY || null;
> 
>   if (url.startsWith('https://') && httpsProxy) {
>     const httpsProxyUrl = new URL(httpsProxy);
>     agent = tunnel.httpsOverHttp({
>       proxy: {
>         host: httpsProxyUrl.hostname,
>         port: parseInt(httpsProxyUrl.port, 10),
>       },
>     });
>     Logger.info(`Using tunnel agent with HTTPS proxy: ${httpsProxy}`);
>   } else if (url.startsWith('http://') && httpProxy) {
>     const httpProxyUrl = new URL(httpProxy);
>     agent = tunnel.httpOverHttp({
>       proxy: {
>         host: httpProxyUrl.hostname,
>         port: parseInt(httpProxyUrl.port, 10),
>       },
>     });
>     Logger.info(`Using tunnel agent with HTTP proxy: ${httpProxy}`);
>   } else {
>     Logger.info(`No proxy settings found or not required for the URL: ${url}. Proceeding without a proxy.`);
>   }
> 
>   const response = await axios.get(url, {
>     headers: {
>       "Content-Type": "application/json",
>     },
>     timeout: universalTimeout,
>     transformResponse: [(data) => data], // Prevent axios from parsing JSON automatically
>     ...(agent ? { httpsAgent: agent, proxy: false } : {}), // set proxy agent
>   });
> ```
> 
> Add the `tunnel` module to `apps/api/Dockerfile`
> 
> ```
> RUN pnpm install
> RUN pnpm add tunnel    # add
> RUN pnpm run build
> ```
> 
> Build with docker compose and start the container.
> 
> ```
> docker compose build && docker compose up -d
> ```
> 
> I hope this helps.

Great solution! When I get to the `RUN pnpm add tunnel` part I'm met with the following:
```
 => => #         │ └── ✕ unmet peer @opentelemetry/api@">=1.0.0 <1.9.0": found 1.9.0
 => => #         ├─┬ @opentelemetry/context-async-hooks 1.24.1
 => => #         │ └── ✕ unmet peer @opentelemetry/api@">=1.0.0 <1.9.0": found 1.9.0
 => => #         └─┬ @opentelemetry/propagator-jaeger 1.24.1 
 => => #           └── ✕ unmet peer @opentelemetry/api@">=1.0.0 <1.9.0": found 1.9.0 
```
Any tips on how to resolve this? Thank you kindly!
