### ISSUE TITLE
[Feat] Fire-engine self hosted?

### ISSUE THREAD

**Issue by furquanh** [mendableai/firecrawl#468]
Thanks for this amazing project. Thank you to all the collaborator who are working on it.

I was curious, in the self-hosted version there's a scraper named fire-engine, is this scraper proprietary to mendable or is it open source?

**Comment by nickscamara** [comment]
Hey @furquanh, thank you! Currently fire-engine is not available for the self hosted version. We are still figuring out the offer there and it is not (yet) open-source.
