### ISSUE TITLE
[Feat] Add Go SDK implementation

### ISSUE THREAD

**Issue by KentHsu** [mendableai/firecrawl#481]
**Proposed Feature**
Based on Python, TypeScript and Rust SDK implementations, I would like to work on Go SDK for Firecrawl.

**Implementation Suggestions**
The implementation will have Go SDK module with tests, examples and README.

**Additional Context**
Seeing the discussion in [Rust SDK PR](https://github.com/mendableai/firecrawl/pull/373#issuecomment-2225606580), I'll try to update GitHub workflow as much as I can.

**Comment by adayNU** [comment]
We would be happy to contribute to this as well.

**Comment by rafaelsideguide** [comment]
@KentHsu That sounds like a great idea! Go for it—I’m excited to see what you come up with haha! Suggestion: ping also @adayNU on your PR so we all get notified by it!

**Comment by KentHsu** [comment]
Sounds great. I'll try to come out a draft PR by the end of this week so we can work on this together.

**Comment by KentHsu** [comment]
@adayNU I have submitted a PR for Go SDK implementation. Please take a look and let me know if there's anything you want to change. Thank you!
