### ISSUE TITLE
[BUG] Doesn't crawl on https://stripe.com/resources/more/banking-as-a-service

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#487]
A YC customer just mentioned that they had issues with this site. Even with ignoreSitemap selected, it only returns one link on the crawl. I verified independently on the playground.

**Comment by calebpeffer** [comment]
Also happening on https://www.perplexity.ai/hub/faq and on intecom help centers

**Comment by nickscamara** [comment]
somewhat related but not fully #477

**Comment by calebpeffer** [comment]
CCing @ankerbachryhl for visibility.

**Comment by nickscamara** [comment]
#491 solves the perplexity one

**Comment by nickscamara** [comment]
`crawlerOptions. allowBackwardCrawling = True` works for crawling stripe starting with that base Url

ccing @ankerbachryhl @calebpeffer

Let us know if you have any questions. Closing this for now.

Thanks @rafaelsideguide
