### ISSUE TITLE
[Feat] Post to a Webhook once a crawl is finished (instead of expecting us to check the crawl status)

### ISSUE THREAD

**Issue by AslanGoldenhour** [mendableai/firecrawl#488]
**Problem Description**
It sucks that we have to check a crawl's status in a looped timer.

**Proposed Feature**
Add the ability to include a webhook callback URL in our crawl payload. That way you can trigger the callback as soon as the crawl is done. This would be waaaaaaaaay more efficient than us pooling for a completed status.

**Alternatives Considered**
- Checking the crawl status. 🤢
- Scraping instead of crawling. 🤮

**Implementation Suggestions**
Use Prisma Pulse or DB triggers to callback to the webhook as soon as the DB record for the crawl event changes to status == completed.

**Use Case**
The benefits seem obvious, but our use case is that we want to scrape the homepage of every startup in a VCs portfolio. So our crawl event has ~150 [+/- 100] subpages on average. I just want a webhook callback to get called when the crawl is done. That way I can look at all portcos at once and decide which ones we'll dig deeper into. I'd do this as /scrape/ calls but dealing with the rate limit sucks. I'd much rather you deal with rate-limiting the scrapes as part of the crawl event.

**Additional Context**
I think I covered everything. I also have a story that this solution will be better for your servers than me checking the crawl status over and over and over and over on a timed interval.

**Comment by nickscamara** [comment]
@AslanGoldenhour Have you tried to set the webhook URL in https://www.firecrawl.dev/app/account ? We should do a way better job documenting it. Adding an issue for that. But I love your ideas of passing it to the payload itself.

And we are working on the v1 of the API and we will make sure to include that. Let me know if the above solution works for now.

**Comment by AslanGoldenhour** [comment]
Oh damn SMF 🫢. Yup—that totally would work for my use case. I imagine I can route to different code on my end if needed, just based on the webhook response payload. Where might I find a schema for that response payload? Is it the same as when checking the status, or does the webhook one look different?

**Comment by nickscamara** [comment]
@AslanGoldenhour awesome! Should be the same.

**Comment by nickscamara** [comment]
#490
