### ISSUE TITLE
Firecrawl is blocked by Cloudflare

### ISSUE THREAD

**Issue by VakhoGeoLab** [mendableai/firecrawl#495]
**Problem Description**
Firecrawl is a nice tool but it is stopped by the free CloudFlare bot protection service.

**Proposed Feature**
If Firecrawl could bypass cloudflare, it could be unstoppable service.

**Comment by khemiri-mohamed** [comment]
i can bypass cloudflare ping me i will prepare what you need

**Comment by JakobStadlhuber** [comment]
@VakhoGeoLab  do you use the self hosted or the cloud version?

**Comment by VakhoGeoLab** [comment]
I’ve tried both. Selfhosted from my computer and also used playground for
testing and cloudflare bot protection works.

**Comment by nickscamara** [comment]
ccing @tomkosm here

**Comment by nickscamara** [comment]
@VakhoGeoLab which URLs are getting blocked?

**Comment by VakhoGeoLab** [comment]
I'm testing https://coinmania.ge a crypto exchange. I'm building the bot for checking crypto prices.

**Comment by PaluchowskiMatthew** [comment]
Same with [https://www.crunchbase.com/](https://www.crunchbase.com/)

**Comment by iuliaturc** [comment]
It also gets blocked by Cloudflare when trying to scrape any subpages of https://jax.readthedocs.io/en/latest/

**Comment by nickscamara** [comment]
@tomkosm can you look into those as soon as you get a chance? tks

**Comment by tomkosm** [comment]
> It also gets blocked by Cloudflare when trying to scrape any subpages of https://jax.readthedocs.io/en/latest/

Hey,
I am not able to replicate this, it seems to work for me now. Cloudflare has different triggers for the high protection modes, try again and let me know if you encounter this issue again, also please provide the exact link and the error you got.

**Comment by tomkosm** [comment]
> I'm testing https://coinmania.ge a crypto exchange. I'm building the bot for checking crypto prices.

This website requires cloudflare captcha solving to access, working on it but cant guarantee that we will be able to support it.

**Comment by hamadzkii** [comment]
can firecrawl bypass the cloudfare captcha or not?

**Comment by anik8das** [comment]
Also seeing this on https://www.wbmason.com 
Any update on whether this is solvable?

**Comment by AIEngKenn** [comment]
Any update about this issue?

**Comment by zcode-apps** [comment]
same here

**Comment by skrewn-dev** [comment]
same here - happening to me also

**Comment by sekedus** [comment]
[scrapling](https://github.com/d4vinci/Scrapling) ?

**Comment by AminDhouib** [comment]
https://github.com/DevinoSolutions/stealth-chrome-devtools-mcp

Specifically made to solve this exact problem to bypass Cloudflare and other captchas for MCP browsing

https://github.com/user-attachments/assets/c4de61ae-6878-4fff-9bfd-65cdd4fadc2f
