### ISSUE TITLE
[BUG] /crawl doesn't work on Samsara.com/ and https://developers.samsara.com/reference/overview

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#513]
Crawl isn't working on samsara.com or developers.samsara.com. Returns only 1 link. Tried typical fixes (waitFor, ignoreSitemap, etc)

**Comment by rafaelsideguide** [comment]
Hey @calebpeffer, I checked the progress for samsara.com and managed to retrieve the `partial_data` during the process, which took about 1.5 hours. The crawler successfully scraped all 6,295 pages, but now that the process is complete, I'm getting `data=null` from crawl check status. Additionally, I couldn't find the job data on supabase, which suggests there might have been an error in attempting to save this large amount of data.

I'm currently looking into ways to improve our process for saving job data on supabase.

**Comment by rafaelsideguide** [comment]
Hey @calebpeffer, I've resolved a bug with the playground request, and now you can crawl samsara.com without any issues.

Regarding the developers' webpage, none of the links on this page are children of `/reference/overview`. I tested this by requesting with `crawlerOptions.allowBackwardCrawling: true` (which is no longer available on the playground), and it successfully retrieved the links.

**Comment by calebpeffer** [comment]
Thanks @rafaelsideguide. Relayed this to the customer!
