### ISSUE TITLE
[Feat] Run actions like clicking, scrolling or advanced waiting on page before extraction

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#517]
I've had a few prospects/customers ask me if we could allow them to run Javascript and actions on the page before we extract the data, such as scrolling the page to access content or clicking on an element.

**Comment by calebpeffer** [comment]
Yeah this has been +1'd already

**Comment by calebpeffer** [comment]
another +1

**Comment by calebpeffer** [comment]
+1

**Comment by calebpeffer** [comment]
+1

**Comment by mrruby** [comment]
+1

I want to scrap booking eg:

https://www.booking.com/searchresults.pl.html?ss=Warsaw&checkin=2024-10-04&checkout=2024-10-06&group_adults=4&no_rooms=1&group_children=0&order=price&nflt=ht_id%3D201%3Broomfacility%3D38

but I need more data that will load on scroll

**Comment by nickscamara** [comment]
This got released!

**Comment by semajkyma** [comment]
How do we do this using the API or console?
