### ISSUE TITLE
[Feat] Add automatic retries to failed links on crawl

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#518]
I've had a few customers who are concerned with the few failures they experience during long crawl jobs. Some have even implemented their own automatic retry functionality. 

If we handle this automatically, we improve reliability and prevent customers from having to implement this themselves.

**Comment by mogery** [comment]
crawl-to-scrape conversion will make this super easy!

**Comment by nickscamara** [comment]
Fixed!
