### ISSUE TITLE
[Feat] What will happen to the links that uses authentication services?

### ISSUE THREAD

**Issue by plushpluto** [mendableai/firecrawl#519]
There are links that uses multiple authentication services behind the scenes, which require either automated or manual intervention. How can I deal with this situation?

**Comment by rafaelsideguide** [comment]
Currently, Firecrawl can handle authentications using the `pageOptions.headers` parameter (check the docs [here](https://docs.firecrawl.dev/api-reference/endpoint/scrape)). However, it does not yet support multiple authentications involving different cookies. We are developing SmartCrawl, which will allow for manual interventions in the future.
