### ISSUE TITLE
[Feat] Can I use this locally? If yes, then do I have to still pay for the sevices? 

### ISSUE THREAD

**Issue by appydam** [mendableai/firecrawl#525]
Will it be free to use if I run this locally?

**Comment by rafaelsideguide** [comment]
Hey @appydam !

Absolutely, you can use Firecrawl locally and it's free under the AGPL license. For many scraping tasks, tools like `fetch` and `playwright` will do the job and you can set this up by following our self-host guide here: [Self-Host Guide](https://docs.firecrawl.dev/contributing/self-host).

Just a heads-up though, if you're looking to use some of our more advanced features like Fire-Engine, those are available through our API and might involve some costs. You can learn more about these features on our blog: [Introducing Fire-Engine for FireCrawl](https://www.firecrawl.dev/blog/introducing-fire-engine-for-firecrawl).

I'm closing this issue for now. Feel free to reopen it if you have any other questions.
