### ISSUE TITLE
[BUG] Certain videos in Iframe's aren't being captured 

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#528]
https://www.liveflow.io/product-guides/how-to-disable-links-to-quickbooks. It's a Loom video; funnily enough, there are other videos in the same format that seem to work on the site. 

Tried:

* adding a timeout of 2000
* changing include/exclude tag settings
 
 Possible issues:
 
 * Timeout still not enough
 * Something weird with iframes?

**Comment by calebpeffer** [comment]
https://help.owner.com/en/articles/8995402-how-to-add-categories-to-a-menu

CCing @samirsen for visibility

**Comment by rafaelsideguide** [comment]
closed by #855
