### ISSUE TITLE
[BUG] go-sdk module name does not match with project structure

### ISSUE THREAD

**Issue by KentHsu** [mendableai/firecrawl#533]
**Describe the Bug**
The module name in [go.mod](https://github.com/mendableai/firecrawl/blob/main/apps/go-sdk/go.mod#L1) does not reflect the project structure. This leads to package import problem.

**To Reproduce**
Go tool does not download this go-sdk when running `go get github.com/mendable/firecrawl` command

**Expected Behavior**
Run `go get github.com/mendable/firecrawl` command should download this go-sdk (with a pseudo-version)
We should be able to see this go-sdk on [Go Packages](pkg.go.dev)

**Screenshots**
![image](https://github.com/user-attachments/assets/eecb5e5f-f60b-4b6b-85ff-98dc6cb47572)

**Comment by KentHsu** [comment]
Hi @ericciarla, The issue still persists. I'm having a hard time making Go tools able to locate go-sdk in subdirectory. Is it possible to move go-sdk to a standalone project under mendableai? We can name it `firecrawl-go` so users can download Firecrawl go-sdk by `go get github.com/mendableai/firecrawl-go`.

**Comment by ericciarla** [comment]
Hi @KentHsu have you tried using Go modules or adjusting the import path? Ideally we want it in the mono repo bc it is easier to maintain.

**Comment by nickscamara** [comment]
Reopening for visibility. @rafaelsideguide feel free to jump in here

**Comment by nickscamara** [comment]
added some comment on the closed pr (not sure if that helps) https://github.com/mendableai/firecrawl/pull/534

**Comment by rafaelsideguide** [comment]
@nickscamara tested here. Didn't work. I'm creating a repo for the go sdk
