### ISSUE TITLE
[Question] Where does the crawl job status data store?

### ISSUE THREAD

**Issue by Z-ZHHH** [mendableai/firecrawl#556]

**Comment by rafaelsideguide** [comment]
@Z-ZHHH I don’t quite understand the question. Could you please elaborate?

**Comment by Z-ZHHH** [comment]
Sorry for the confusion in my previous question. What I'm trying to understand is how multiple crawl jobs running simultaneously manage their partial data, such as the HTML content of crawled URLs. Specifically, where is this partial data stored—either in memory or as files on disk? Thank you.

**Comment by rafaelsideguide** [comment]
No problem at all! To clarify:

If you're self-hosting, the partial data is stored in Redis.
If you're using our API, the partial data is saved in Supabase.

I hope this helps! I'm closing this issue for now, but feel free to reopen it or reach out if you have any other questions.
