### ISSUE TITLE
[BUG] docs.stripe.com return null after 2800 scrapes

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#568]
Runs the crawler on https://docs.stripe.com/, it discovers around 2800 pages shows the crawl progress, but after it's done crawling, it just returns an array full of null values

**Comment by rafaelsideguide** [comment]
v1/crawl fixes that. Closing for now. @calebpeffer feel free to reopen this issue if you receive any other feedback on this topic.
