### ISSUE TITLE
[BUG] Search endpoint includes extra content in extracted titles

### ISSUE THREAD

**Issue by danielmahon** [mendableai/firecrawl#569]
**Describe the Bug**
The SEARCH endpoint will sometimes append extra "title" data to the page title. It seems as though the title matching solution is too inclusive and will pickup multiple "<title>" tags in the html code. When it should probably only use the main "root" one.

This can result in mutated titles:
- https://www.trade.gov/market-intelligence/australia-artificial-intelligence-market: Australia Artificial Intelligence MarketThis link will direct you to a non-government websiteThis link will direct you to a non-government websiteThis link will direct you to a non-government websiteThis link will direct you to a non-government website
- https://www.csiro.au/en/work-with-us/industries/technology/national-ai-centre: National Artificial Intelligence Centre - CSIROBlog icon

**To Reproduce**
Steps to reproduce the issue:
1. Search "Australian Artificial Intelligence industry bodies" or any search including the following sites:
  - https://www.trade.gov/market-intelligence/australia-artificial-intelligence-market
  - https://www.csiro.au/en/work-with-us/industries/technology/national-ai-centre

**Expected Behavior**
The extracted title should only include the main title tag:
- Australia Artificial Intelligence Market
- National Artificial Intelligence Centre - CSIRO

**Comment by rafaelsideguide** [comment]
`/search` endpoint was deprecated on v1. Closing this one.
