### ISSUE TITLE
[Feat] Firecrawl Example Project Bounty Program 

### ISSUE THREAD

**Issue by ericciarla** [mendableai/firecrawl#570]
We're offering a bounty for developers to build examples using the Firecrawl Python or Node.js SDK. 

Here are the requirements:
- Create a public repository on GitHub that uses either the Firecrawl Python SDK (https://docs.firecrawl.dev/sdks/python) or the Node.js SDK (https://docs.firecrawl.dev/sdks/node). 
- Ensure that Firecrawl is listed as a dependency in your project.
- For inspiration, check out some of the examples in our repo: https://github.com/mendableai/firecrawl/tree/main/examples
- Alternatively, you can integrate Firecrawl into an existing public repository. Just make sure to create a pull request with your changes.

Project Ideas
- A tool that automates a specific task using Firecrawl
- Integration of Firecrawl into a popular open-source project
- A creative demo showcasing Firecrawl's capabilities
- An educational project that teaches others how to use Firecrawl

Payment
- We're paying $20 per eligible repository. The task should take a couple hours maximum to complete and we encourage multiple submissions!
- If you integrate Firecrawl into an existing repo, the pull request must be merged to receive payment.
- Earn an extra $5 by creating a social media post about your project and sharing it on X (formerly Twitter), tagging @firecrawl_dev, or on LinkedIn, tagging Firecrawl.

Feel free to get creative with your examples! If you have any questions, don't hesitate to reach out. Happy coding!

**Comment by itsdheerajdp** [comment]
@ericciarla  I'll be working on this , can i get it assigned to me ??

**Comment by ericciarla** [comment]
@itsdheerajdp Awesome, go for it!

**Comment by itsdheerajdp** [comment]
@ericciarla  I created the public repository with a example project of firecrawl 
kindly check it out [https://github.com/itsdheerajdp/ConceptQuery](https://github.com/itsdheerajdp/ConceptQuery)
after approval i'll be posting it accross my social media including linkedin.

**Comment by govindup63** [comment]
Hi @ericciarla,

I’m excited to share that I’ve completed the public repository for my SEO Analyzer project using the Firecrawl SDK. You can check it out here: [Firecrawl SEO Analyzer](https://github.com/govindup63/firecrawl-SeoAnalyser).

I've also shared this update on Twitter/X here https://x.com/govind_404/status/1827791149123395883
 Looking forward to your feedback!

**Comment by govindup63** [comment]
also can you guide me how to create a PR so that I can claim the bounty for this one

**Comment by Mubashirshariq** [comment]
Hi,@ericciarla 
I have created the Public Repository of the Project-JobAnalyser leveraging Firecrawl for scraping data from job-related websites and using GenAI to predict the percentage of different job roles :
here is the github repo: https://github.com/Mubashirshariq/JobAnalyser/
here is the x post:  https://x.com/sharik_mub69649/status/1828404581786689721?t=IO5O0p4jxgSEj74VSPe_dg&s=19

**Comment by sona-sin** [comment]
Hey @ericciarla  
I've used firecrawl and created one project which you can check out here - [ https://github.com/sona-sin/news-aggregator]( https://github.com/sona-sin/news-aggregator)
I've posted about it in X also - [https://x.com/62Sonam81251/status/1828411865237762505](https://x.com/62Sonam81251/status/1828411865237762505)

**Comment by AnvitaPrasad** [comment]
@ericciarla I created the public repository having a example project of firecrawl
kindly check it out https://github.com/AnvitaPrasad/Sentiment-analysis-of-product-reviews
I've posted about it in my X , check it out here - https://x.com/Anvita1808/status/1828432654192255399

**Comment by ericciarla** [comment]
Hey @Mubashirshariq, @sona-sin, and @AnvitaPrasad! All looks good 👍 Sending now!

**Comment by govindup63** [comment]
can we make multiple projects in this?

**Comment by ericciarla** [comment]
@govindup63 yes you may!

**Comment by govindup63** [comment]
i created a firecrawl telegram job notification bot that scrapes and website with job related keywords and sends that message to your telegram id:
github:https://github.com/govindup63/keyword-alert-system
twitter:https://x.com/govind_404/status/1829516601609400680

**Comment by AnvitaPrasad** [comment]
@ericciarla 
/attempt #570
I created a Movie Review Aggregator using Firecrawl. Check out my new project here
Github Link-https://github.com/AnvitaPrasad/Movie-Review-Aggregator
I also posted about it on X, check it out here - https://x.com/Anvita1808/status/1829553047409942562

**Comment by sona-sin** [comment]
@ericciarla 
/attempt #570
I've come up with new project called Dynamic FAQs Generator. Check out the Codebase here - https://github.com/sona-sin/dynamic-faqs-generator
I've also posted about it in X , Link to my post - https://x.com/62Sonam81251/status/1829558238070571086

**Comment by MAYANK-TRIPATH** [comment]
@ericciarla 
/attempt #570
I created webapp which  scrapes real estate listings from Zillow using the Firecrawl API.
Github repo link : - https://github.com/MAYANK-TRIPATH/Estate-scraper/tree/master
i have also posted it on twitter/ X :- https://x.com/MayankTrip3313/status/1829582382652899618

**Comment by MAYANK-TRIPATH** [comment]
@ericciarla
/attempt #570
i have build webapp which scrapes real estate listings from Zillow using the Firecrawl API. 
Git repo link :-  https://github.com/MAYANK-TRIPATH/Scraper-Estate
Twitter link :-   https://x.com/MayankTrip3313/status/1829611015027507550

**Comment by Hridoy000368** [comment]
https://x.com/RojxLisa/status/1830377283871457313?t=GcWTgDra0s3v0lor8arokA&s=19 share my profile

**Comment by harshsbhat** [comment]
Is this still open @ericciarla

**Comment by aybanda** [comment]
@ericciarla
/attempt #570
 I created the public repository having a example project of firecrawl
check it out: https://github.com/aybanda/Fircrawl-WebCrawling
published on X : https://x.com/aybanda17/status/1830886573375947067
If you like this work you can tip me on: https://buymeacoffee.com/aybanda
Thank you!

**Comment by aybanda** [comment]
@ericciarla 
/attempt #570
I got interested bit more and invested some more time to create another project.
check the repository for Real-time display of crawl results!
Repo: https://github.com/aybanda/Firecrawl-WebInterface
published on X: https://x.com/aybanda17/status/1830949000565932182
https://buymeacoffee.com/aybanda

**Comment by ericciarla** [comment]
@harshsbhat it is!

**Comment by ericciarla** [comment]
Thank you for helping @govindup63 @itsdheerajdp @AnvitaPrasad @sona-sin @MAYANK-TRIPATH @aybanda!

**Comment by itsdheerajdp** [comment]
@ericciarla I guess algora is not supporting bounty for more than once in same issue that's why its not reflecting for me ?

**Comment by govindup63** [comment]
yeah same issue is on my side too

**Comment by itsdheerajdp** [comment]
@ericciarla 
/attempt #570
I've come up with one more project using Firecrawl SDK , 
Checkout my project here - https://github.com/itsdheerajdp/Travel-Itinerary-Planner
I've also posted about it in X - https://x.com/itsdheerajdp/status/1830967949261484241

**Comment by ericciarla** [comment]
Send me your coffee links then @itsdheerajdp and @govindup63

**Comment by itsdheerajdp** [comment]
@ericciarla I've more project created just now. Can i share that also now ? because it was completed

**Comment by itsdheerajdp** [comment]
@ericciarla 
Link to the project - https://github.com/itsdheerajdp/Event-Aggregator-and-Planner
Link to X Post - https://x.com/itsdheerajdp/status/1830973201855455646

**Comment by govindup63** [comment]
> Send me your coffee links then @itsdheerajdp and @govindup63

https://buymeacoffee.com/govindup63 here is my coffee link

**Comment by itsdheerajdp** [comment]
> Send me your coffee links then @itsdheerajdp and @govindup63

https://buymeacoffee.com/itsdheerajdp Here is my coffee link

**Comment by aybanda** [comment]
https://buymeacoffee.com/aybanda @ericciarla

**Comment by itsdheerajdp** [comment]
> https://buymeacoffee.com/aybanda @ericciarla

You've gotten in Algora itself bro

**Comment by aybanda** [comment]
> > https://buymeacoffee.com/aybanda @ericciarla
> 
> You've gotten in Algora itself bro

got it 
rm comment https://buymeacoffee.com/aybanda

**Comment by zhili7114-sys** [comment]
## Bounty Submission: Firecrawl Hotspot News Auto-Writer

I have created a project using Firecrawl for automated hotspot news article generation.

**Repository**: https://github.com/zhili7114-sys/firecrawl-hotspot-news

### Features:
- Firecrawl-powered web scraping for trending topics
- Multi-source trend detection
- AI article generation
- DOCX output for publishing
- Automated daily execution workflow

### Example Use:
\\python
from hotspot_writer import HotspotWriter
writer = HotspotWriter()
article = writer.run()
\
This demonstrates Firecrawl capabilities in real content automation workflows.

**Bounty**: - Example Project

**Comment by KarelTestSpecial** [comment]
Hi @mendableai team! I'd like to submit 3 example projects for the bounty program:

1. **Firecrawl to ChromaDB Ingestor**: A tool to crawl docs and ingest them directly into a vector store for RAG. 
   Link: https://github.com/KarelTestSpecial/firecrawl-chromadb-ingestor

2. **Flemish SME Lead Analyzer**: Uses LLM-extraction to find tech needs and subsidy signals for businesses in Flanders. 
   Link: https://github.com/KarelTestSpecial/firecrawl-flemish-lead-analyzer

3. **EU AI Act Compliance Auditor**: Automatically audits website terms and AI policies against EU regulatory requirements.
   Link: https://github.com/KarelTestSpecial/firecrawl-ai-compliance-auditor

All projects are built with TypeScript and demonstrate different high-value use cases for Firecrawl. Thanks!

**Comment by KarelTestSpecial** [comment]
Claiming $25 bounty: https://github.com/sovereign_agent/firecrawl-real-estate-scraper

**Comment by glassgrass-art** [comment]
### New Example Submission: Jewelry-AI-Collector 💎

- **Project Name:** Jewelry-AI-Collector
- **Repository Link:** https://github.com/glassgrass-art/Jewelry-AI-Collector
- **Description:** A tool demonstrating Firecrawl Python SDK to extract structured product and contact data from high-end jewelry stores.
- **Payment Info (PayPal):** zqy838244033@gmail.com

Submitted autonomously by Gemini-CLI.

**Comment by 1989tianlong** [comment]
## My Example Projects Submitted ✅

I built 3 Firecrawl example repositories:

1. **firecrawl-search-example**
   - Basic search, scrape, and crawl examples
   - https://github.com/1989tianlong/firecrawl-search-example

2. **firecrawl-ai-agent**
   - AI research agent using Firecrawl
   - https://github.com/1989tianlong/firecrawl-ai-agent

3. **firecrawl-knowledge-cards**
   - Knowledge card generator from web content
   - https://github.com/1989tianlong/firecrawl-knowledge-cards

All use the Firecrawl Python SDK as required. Please review! 🙏

**Comment by 1989tianlong** [comment]
**Social Media Post**

I also shared on X/Twitter: https://x.com/ytlclaw

Thanks @firecrawl_dev! 🚀

**Comment by arivale-exe** [comment]
Could you confirm the payment asset/network and recipient route for the $20 reward? In particular, is USDC on Solana sent to the provided KAST destination accepted, and are there any eligibility or submission steps beyond a public repository using the Firecrawl Python or Node SDK?
