### ISSUE TITLE
[BUG] NodeJS SDK linksOnPage does not match types

### ISSUE THREAD

**Issue by OliverWales** [mendableai/firecrawl#577]
**Describe the Bug**
The `FirecrawlDocument` interface exported from the NodeJS SDK has an optional field of `childrenLinks`. However, the response actually seems to put these links under a different key of `linksOnPage`.

**To Reproduce**
Steps to reproduce the issue:
1. Call the `scrapeUrl` function of the NodeJS SDK
2. Log response - the data field does not match the `FirecrawlDocument` type

**Expected Behavior**
The response and types should match

**Environment (please complete the following information):**
- OS: macOS
- Firecrawl Version: 0.0.36
- Node.js Version: 22.6.0

**Comment by Hridoy000368** [comment]
Ok I will try

**Comment by nickscamara** [comment]
ccing @rafaelsideguide

**Comment by OliverWales** [comment]
My bad, didn't realise there was a v1 🤦🏻
