### ISSUE TITLE
f1dfab7b-b064-4dc9-b671-0f9afbaa80f8

### ISSUE THREAD

**Issue by Hridoy000368** [mendableai/firecrawl#585]
**Describe the Bug**
Provide a clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the issue:
1. Configure the environment or settings with '...'
2. Run the command '...'
3. Observe the error or unexpected output at '...'
4. Log output/error message

**Expected Behavior**

**Screenshots**
If applicable, add screenshots or copies of the command line output to help explain the issue.

**Environment (please complete the following information):**
- OS: [e.g. macOS, Linux, Windows]
- Firecrawl Version: [e.g. 1.2.3]
- Node.js Version: [e.g. 14.x]

**Logs**
If applicable, include detailed logs to help understand the problem.

**Additional Context**
Add any other context about the problem here, such as configuration specifics, network conditions, data volumes, etc.

**Comment by rafaelsideguide** [comment]
@Hridoy000368 you didn't describe the issue. Closing.
