### ISSUE TITLE
[Bug] www.churchofjesuschrist.org/study/manual/missionary-standards-for-disciples-of-jesus-christ?lang=eng doesn't get all links

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#589]
This website only gets a few links with default parameters

[www.churchofjesuschrist.org/study/manual/missionary-standards-for-disciples-of-jesus-christ?lang=eng](https://www.churchofjesuschrist.org/study/manual/missionary-standards-for-disciples-of-jesus-christ?lang=eng)

**Comment by rafaelsideguide** [comment]
@calebpeffer This page is a deep URL, which might be why the customer isn't getting the expected results. If you run the crawl with `allowBackwardLinks: true`, you'll see that the crawler finds more than 10k pages (10k is the default limit for a crawl).

```json
{
  "status": "scraping",
  "completed": 1241,
  "total": 10000,
  "creditsUsed": 10000,
  ...
 }
 ```
