### ISSUE TITLE
[Feat] Page Localization

### ISSUE THREAD

**Issue by ad-angelo** [mendableai/firecrawl#597]
**Problem Description**
Some pages don't match my position. So language and currency are different from mine.
For the most part, the country code is inside the link but for some, I think it's based on the IP address of your servers.

**Proposed Feature**
How to force position for this type of pages ?

Would it be possible to select the country code ?

**Comment by nickscamara** [comment]
@ad-angelo We're working on it!

ccing @tomkosm 

Another customer also requested this +1

**Comment by tomkosm** [comment]
Hey @ad-angelo ,
Most websites choose the language based on Accept-Language header, you can set this on firecrawl with the header argument in scrape. We dont support regional proxies at the moment, but this header will probably do it.

**Comment by nickscamara** [comment]
We launched support for geo-location this week! Check it out here! https://docs.firecrawl.dev/launch-week#day-2-geolocation

@ad-angelo @mschfh
