### ISSUE TITLE
401 when checking job status

### ISSUE THREAD

**Issue by menguzat** [mendableai/firecrawl#6]
I'm trying to use the example.js you provided in the repo.

```
import FirecrawlApp from '@mendable/firecrawl-js';

const app = new FirecrawlApp({apiKey: "my api key"});

const crawlResult = await app.crawlUrl('docs.babylonjs.com', {crawlerOptions: {excludes: ['blog/*'], limit: 10}}, false);
console.log(crawlResult)

const jobId = await crawlResult['jobId'];


let job;
while (true) {
    console.log("checking ",app.apiKey);
  job = await app.checkCrawlStatus(jobId);
  if (job.status == 'completed') {
    break;
  }
  console.log(job);
  await new Promise(resolve => setTimeout(resolve, 1000)); // wait 1 second
}

console.log(job.data[0].content);

```

I get 

{ jobId: '678757b8-0d03-4c56-8017-a6b04136ad07' }
checking  fc-4a0f64912306448c975701198d28b85e
file:///D:/Web/webscraper/node_modules/@mendable/firecrawl-js/build/index.js:91
                throw new Error(error.message);
                      ^

Error: Request failed with status code 401
    at FirecrawlApp.<anonymous> (file:///D:/Web/webscraper/node_modules/@mendable/firecrawl-js/build/index.js:91:23)
    at Generator.throw (<anonymous>)
    at rejected (file:///D:/Web/webscraper/node_modules/@mendable/firecrawl-js/build/index.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

It seems like it starts to crawl but when checking the job, it gets a 401. why might that be?

**Comment by nickscamara** [comment]
@menguzat all fixed. Thanks for reporting it!
