### ISSUE TITLE
[Feat] Hide scrollbars from screenshots

### ISSUE THREAD

**Issue by OliverWales** [mendableai/firecrawl#600]
**Problem Description**
Screenshots returned from the API have visible scrollbars.

**Proposed Feature**
Native scrollbars are hidden in screenshots.

**Alternatives Considered**
Or keep them, but they would look cleaner without.

**Implementation Suggestions**
I expect this is just a config option on the headless browser.

**Use Case**
Make screenshots look prettier when embedded in my dashboard.

**Additional Context**
Seems like this is the default in Puppeteer.

**Comment by mogery** [comment]
Hey Oli, thanks for reporting! I've got a preliminary fix for this and we're going to be testing it soon.
