### ISSUE TITLE
[BUG] "Environment Variable USE_DB_AUTHENTICATION Incorrectly Interpreted as Truthy, Causing playwright Scraper Exclusion"

### ISSUE THREAD

**Issue by yekkhan** [mendableai/firecrawl#610]
**Describe the Bug**
When configuring the environment variable USE_DB_AUTHENTICATION, its value is being interpreted as a string "false" instead of a boolean false. This causes conditional logic that checks process.env.USE_DB_AUTHENTICATION to incorrectly evaluate as truthy, even when the value is set to "false". As a result, the application includes or excludes certain scrapers based on incorrect logic.

**To Reproduce**
Steps to reproduce the issue:
1. Configure the environment variable #USE_DB_AUTHENTICATION with the value false in your environment configuration 
2. docker compose build and docker compose up
3. The function getScrapingFallbackOrder in apps/api/src/scraper/WebScraper/single_url.ts will never include playwright as a scraper option because process.env.USE_DB_AUTHENTICATION is always treated as true whenever it is set, regardless of whether its value is "true" or "false". 

**Expected Behavior**
The environment variable USE_DB_AUTHENTICATION should be correctly interpreted as a boolean false when set to "false" in the environment configuration. Conditional logic should properly evaluate process.env.USE_DB_AUTHENTICATION as falsy, and the application should exclude scrapers or perform actions accordingly.

**Screenshots**
If applicable, add screenshots or copies of the command line output to help explain the issue.
![image](https://github.com/user-attachments/assets/b7203c92-65ac-4488-a81c-151473fe47e5)

**Comment by nickscamara** [comment]
Just merge the fix @yekkhan! #516 

Thank you!

**Comment by yekkhan** [comment]
thx @nickscamara !
