### ISSUE TITLE
[EXAMPLE BOUNTY] Firecrawl Python Example Program

### ISSUE THREAD

**Issue by ericciarla** [mendableai/firecrawl#616]
# Firecrawl Example Bounty Program

We're offering a bounty for developers to build examples using the Firecrawl Python SDK. We're especially interested in high-quality projects with comprehensive READMEs or tutorial-style examples that we can merge into our examples folder.

## Requirements

* Create a public repository on GitHub that uses the Firecrawl Python SDK (https://docs.firecrawl.dev/sdks/python).
* Ensure that Firecrawl is listed as a dependency in your project.
* For inspiration, check out some of the examples in our repo: https://github.com/mendableai/firecrawl/tree/main/examples
* Alternatively, you can integrate Firecrawl into an existing public repository. Just make sure to create a pull request with your changes.
* **IMPORTANT**: You MUST submit a video demonstrating your project in action. This video should clearly show the functionality and usage of your Firecrawl integration.

## Payment and Bonuses

* Base payment: $20 per eligible repository. We encourage multiple submissions!
* Payment method: Via Buy Me a Coffee. Please set up your account and include the link with your submission.
* **Limit**: Each person is eligible for payment for up to 3 projects. For additional paid projects beyond this limit, please contact eric@firecrawl.com.

### Additional bonuses are available for:

* Projects of equal or higher quality than our /examples folder (with potential for merging into our repo)
* Tutorial-style examples with clear explanations
* Innovative use cases of the Firecrawl Python SDK
* Social media promotion:
  - Earn an extra $5 by posting about your project on X (formerly Twitter) and tagging @firecrawl_dev, or on LinkedIn and tagging Firecrawl.
  - Receive an additional $5 for every 1000 views on your social media post about the project.

## Submission Process

1. Complete your project and push it to a public GitHub repository.
2. Create a video demonstration of your project in action.
3. Submit your project by replying to this issue with:
   - The link to your GitHub repository
   - The video demonstration
   - Your buy me a coffee link
   - Any social media posts you've made about the project (if applicable)

Feel free to get creative with your examples! If you have any questions, don't hesitate to reach out. Happy coding!

## Note for High-Quality Project Creators

For very high-quality project creators, we may offer a residency program. If you're interested in this opportunity, please contact eric@firecrawl.com after completing your initial projects.

**Comment by harshsbhat** [comment]
@ericciarla  Built a autodetect website language to Spanish translator using Firecrawl and Azure API.  

Repo: https://github.com/harshsbhat/translify

Video: https://www.loom.com/share/842f3de485784a9ca8eaefb711d7e02f?sid=52d0f8d1-fe1c-4c0b-84f7-87642116a49b

Tweet: https://x.com/HarshBhatX/status/1831031294781968608

**Comment by harshsbhat** [comment]
@ericciarla  Built a Website to Markdown file using OpenAI and Firecrawl python sdk. 

Repo: https://github.com/harshsbhat/arcax

Video:  

https://www.loom.com/share/d565163ab6e345f2b3239b32e676cfc4?sid=7efde3a6-2fb3-4c0e-9e80-931d09158184


Tweet: 
https://x.com/HarshBhatX/status/1831188449417728417


Buymeafcoffee: https://buymeacoffee.com/harshbhat

**Comment by aybanda** [comment]
@ericciarla Built a website for Web Content Visualization Dashboard using firecrawl python sdk.
Github Repo: https://github.com/aybanda/Firecrawl-VisualDashboard/tree/master
Functioning Video: https://www.loom.com/share/fca583d15cdd43cc82354e1873ceabaa
On X: https://x.com/aybanda17/status/1831297176808591580

Buy me a Coffee: https://www.buymeacoffee.com/aybanda

**Comment by aybanda** [comment]
@ericciarla  Built Web Accessibility Analyzer is a Streamlit-based web application that helps developers and content creators assess the accessibility of their websites.

Github Repo: https://github.com/aybanda/Firecrawl-WebAccessibilityAnalyzer/tree/main

Functioning video:

 https://www.loom.com/share/f6acfc8c58884a888e2a2d53620dff07

published on X: https://x.com/aybanda17/status/1831307126536585641


Buy me a Coffee: https://www.buymeacoffee.com/aybanda

**Comment by harshsbhat** [comment]
> Thanks for completing these @aybanda + @harshsbhat! Just a note, we are limiting paid projects to 3 per creator.  

Sure I am working on the third one. Thanks for letting us know in advance 😃

**Comment by harshsbhat** [comment]
> Thanks for completing these @aybanda + @harshsbhat! Just a note, we are limiting paid projects to 3 per creator.  

Received the tip. Thanks a lot

**Comment by aybanda** [comment]
@ericciarla Built Content Readability Scorer, It uses the Firecrawl API to fetch web content and applies various readability metrics to provide insights into the complexity and accessibility of the text.

GithubRepo: https://github.com/aybanda/FireCrawl-ContentReadabilityScorer/tree/main

Published on X: https://x.com/aybanda17/status/1831374935065030785

Functioning Video: 

https://www.loom.com/share/b47177e7f0554ac2b6ab04c8b2183c99


Buy me a coffee: https://www.buymeacoffee.com/aybanda


Thanks for the tips @ericciarla

**Comment by govindup63** [comment]
@ericciarla  built an OpenAi based web content analyser
GitHub repo: https://github.com/govindup63/firecrawl-web-content-summarizer.git
published on x: https://x.com/govind_404/status/1831381700494164076
video is attached on github page
Buy me a coffee: https://buymeacoffee.com/govindup63

**Comment by harshsbhat** [comment]
@ericciarla  Built a blog sentiment analysis using Firecrawl: 

GitHub: https://github.com/harshsbhat/sentix

Video: https://www.loom.com/share/237cc669abf44d73bc406709fc0bc5fa?sid=502beb79-3d57-48de-bd4d-2698e48a5fd4

Tweet: https://x.com/HarshBhatX/status/1831547078427775066

Buy me a coffee: https://buymeacoffee.com/harshbhat

**Comment by govindup63** [comment]
@ericciarla I created my second project using Firecrawl's Python SDK and Gemini Api to summarize web content.
Github:https://github.com/govindup63/firecrawl-gemini/tree/master
video:

https://github.com/user-attachments/assets/f585aeb6-23a5-4a27-8f05-94f12e151413

twitter/X : https://x.com/govind_404/status/1832049968523153634

Buy me a coffee: https://buymeacoffee.com/govindup63

**Comment by govindup63** [comment]
@ericciarla my third and final project
This project will help you get the recipe of any dish by using Firecrawl and gemini
it extracts the data of the website containing the dish and then passes it to Gemini for more authentic and safe results 
Github: https://github.com/govindup63/recipe-scraper
X: https://x.com/govind_404/status/1832114750857363923
Buy Me Coffee: https://buymeacoffee.com/govindup63
video:

https://github.com/user-attachments/assets/1b5516e9-0534-4ccd-9af5-0d44f953c216

**Comment by ericciarla** [comment]
Awesome work @govindup63!

**Comment by ericciarla** [comment]
Great work on your example @aybanda

**Comment by ericciarla** [comment]
Good stuff @harshsbhat

**Comment by ericciarla** [comment]
Very cool @aditya-supare

**Comment by aditya-supare** [comment]
@ericciarla Build Security-Analyzer which goes through a website and detects the security issues and provides suggestions as well! 

Github: https://github.com/aditya-supare/Security-Analyzer

Video: https://www.loom.com/share/25a36de786774398b2bc753a611cafee?sid=2bd277c1-1531-43e4-8c9c-6878191b0e97

Tweet: https://x.com/wabi002/status/1832162814687166534

Buy me a coffee: https://buymeacoffee.com/adityasupac

**Comment by aditya-supare** [comment]
@ericciarla Built Personalized book recommendations based on the genres given by the user

Github: https://github.com/aditya-supare/ReadQuest
X: https://x.com/wabi002/status/1832176186807742918
Buy Me Coffee: https://buymeacoffee.com/adityasupac

Video: https://www.loom.com/share/44d93ab87ad946e78bcd97a190d73242?sid=dc539dd8-6f2a-48cd-a40d-8abd561837c8

**Comment by ayaxan7** [comment]
@ericciarla My frist project, built a web content summarization tool that uses the Firecrawl SDK for scraping web content and generate summaries. It allows users to input multiplte URLs at the same time, scrape its content, and get a concise summary .

Github: https://github.com/ayaxan7/firecrawl-content-aggregator
X: https://x.com/SyedMoh28440276/status/1832180442356953170
Buy Me Coffee: https://buymeacoffee.com/ayaann.__.__

https://github.com/user-attachments/assets/66ead8fb-560f-427e-8461-1ca4c644b89e

**Comment by ayaxan7** [comment]
@ericciarla My second project, built this project that scrapes content from specified URLs using Firecrawl SDK, preprocesses the text by removing stopwords and non-alphanumeric tokens, and then analyzes word frequencies to print the most common words.

Github: https://github.com/ayaxan7/Firecrawl-Word-Frequency-Analysis
X: https://x.com/SyedMoh28440276/status/1832193836673880152

Uploading 07.09.2024_04.33.58_REC.mp4…


Buy Me Coffee:https://buymeacoffee.com/ayaannn

**Comment by ayaxan7** [comment]
@ericciarla My second project, built this project that scrapes content from specified URLs using Firecrawl SDK, preprocesses the text by removing stopwords and non-alphanumeric tokens, and then analyzes word frequencies to print the most common words.

Github: https://github.com/ayaxan7/Firecrawl-Word-Frequency-Analysis
X: https://x.com/SyedMoh28440276/status/1832193836673880152


Buy Me Coffee:https://buymeacoffee.com/ayaannn


https://github.com/user-attachments/assets/398ca4af-72da-49ee-be87-7e0737831a42

**Comment by gopal-hash** [comment]
@ericciarla Hey this is my first submission to this project 
Its a travel Itinerary planner which use firecrawl python sdk and gemini api to generate itinarary
Github: https://github.com/gopal-hash/Itinerary-planner/tree/master
X: https://x.com/Govindup63/status/1832194288840798635
Video:

https://github.com/user-attachments/assets/d6edd5ad-3eac-4dae-91d8-6f4ab5773048

Buy me a coffee: https://buymeacoffee.com/gopal.hash

**Comment by gopal-hash** [comment]
@ericciarla this is my second submission to this project. i made a website that give you info about any crypto currency by scrapping data from relevent website and passing it through gemini
Github: https://github.com/gopal-hash/know-your-crypto/tree/master
X:https://x.com/gopal_hash/status/1832202585350066502
Video

https://github.com/user-attachments/assets/a5609221-a6e4-489e-b751-a8c8f91c2dfe

Buy me a coffee: https://buymeacoffee.com/gopal.hash

**Comment by gopal-hash** [comment]
@ericciarla Final project submission 
made a research paper analyser which takes link of the research paper as input the srapes data from the website and then gives you summarised results using gemini
Github: https://github.com/gopal-hash/research-paper-analyser
X: https://x.com/gopal_hash/status/1832208120744996918
Video demo:
https://github.com/user-attachments/assets/6f973a37-fd37-4fc0-9541-20cc8bc20ee6
Buy me a coffee: https://buymeacoffee.com/gopal.hash

**Comment by gopal-hash** [comment]
any updates? @ericciarla

**Comment by ericciarla** [comment]
Great work! Checking out the projects now

**Comment by ericciarla** [comment]
Appreciate all of the submissions! We are going to be closing up this program on Sept 20.

**Comment by govindup63** [comment]
@ericciarla I have few more ideas can I make those or just three submissions are the limit?

**Comment by ericciarla** [comment]
Hi @govindup63, shoot me an email at eric@firecrawl.com!

**Comment by ayaxan7** [comment]
@ericciarla my third and final project
This project scrapes text from a given URL and generates a graphical bar chart of the top 20 most frequent words in the content. It provides a clear visual representation of word frequency to help analyze the text data efficiently.

Github: https://github.com/ayaxan7/firecrawl-word-frequency-analyser/
X: https://x.com/SyedMoh28440276/status/1834296877824836034
Buy Me Coffee: https://buymeacoffee.com/ayaannn
video:

https://github.com/user-attachments/assets/cc67d4ec-0e28-47f3-9efd-b4a12c9dcce5
