### ISSUE TITLE
[docs] Improve types around success/errors on the docs

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#617]
Customer had this issue:

![image](https://github.com/user-attachments/assets/697c903e-4234-42cd-8bc7-62610ca6b8df)

Should be an easy fix?

**Comment by nickscamara** [comment]
It is not an issue, just lack of documentation with the type inheritance. @rafaelsideguide we need docs on { success, error} checks like supabase have.

**Comment by nickscamara** [comment]
I believe this was done intentionally by @rafaelsideguide to force people to check for errors like below
```
const result = await firecrawlApp.scrapeUrl(url, {
            formats: ["markdown"],
          });

          if(!result.success){
            return <Message role="assistant" content={<div>{result.error}</div>} />;
          }
```

**Comment by nickscamara** [comment]
@calebpeffer, @rafaelsideguide will add docs to it asap.

**Comment by nickscamara** [comment]
All pushed!
