### ISSUE TITLE
TypeError: FirecrawlApp.__init__() got an unexpected keyword argument 'version'

### ISSUE THREAD

**Issue by haisheng666** [mendableai/firecrawl#621]
from firecrawl.firecrawl import FirecrawlApp
from pydantic import BaseModel, Field
from typing import List

app = FirecrawlApp(
    api_key="fc-35xxx",
    version="v0"
)

class ArticleSchema(BaseModel):
    title: str
    points: int
    by: str
    commentsURL: str

class TopArticlesSchema(BaseModel):
    top: List[ArticleSchema] = Field(..., max_items=5, description="Top 5 stories")

data = app.scrape_url('https://news.ycombinator.com', {
    'extractorOptions': {
        'extractionSchema': TopArticlesSchema.model_json_schema(),
        'mode': 'llm-extraction'
    },
    'pageOptions': {
        'onlyMainContent': True
    }
})
print(data["llm_extraction"])

There is a problem running your official website example
TypeError: FirecrawlApp.__init__() got an unexpected keyword argument 'version'

**Comment by nickscamara** [comment]
Fixed, thanks for letting us know. Version is no longer required.
