### ISSUE TITLE
[BUG] Cant accept connection

### ISSUE THREAD

**Issue by djav1985** [mendableai/firecrawl#622]
[2024-09-04T16:32:18.656Z]INFO - 🐂 Worker taking job 645e1c5d-be56-4954-80be-b79a25ebebbe
Cant accept connection
Cant accept connection
Cant accept connection
[2024-09-04T16:32:24.667Z]DEBUG - Skipping logging scrape to Supabase

Could you please explain why the worker gets the error "Cant accept connection"

**Comment by nickscamara** [comment]
Hey @djav1985, this error occurs when either you don't enough RAM or CPU available in the machine you are running.

**Comment by nickscamara** [comment]
It happens when this is false:
```
public async acceptConnection() {
        const cpuUsage = await this.checkCpuUsage();
        const memoryUsage = await this.checkMemoryUsage();

        return cpuUsage < MAX_CPU && memoryUsage < MAX_RAM;
    }
```

**Comment by djav1985** [comment]
Thank you very much.
