### ISSUE TITLE
[BUG] 500 error downloading logs from dashboard

### ISSUE THREAD

**Issue by ysijason** [mendableai/firecrawl#642]
**Describe the Bug**
500 error downloading logs from dashboard

**To Reproduce**
Dashboard --> Activity --> Download

**Expected Behavior**
should work

**Screenshots**
![image](https://github.com/user-attachments/assets/daa13c54-0f29-4855-9a4f-5ad853a3cafb)

**Environment (please complete the following information):**
Windows 11 - Chrome

**Logs**
If applicable, include detailed logs to help understand the problem.

**Additional Context**
Add any other context about the problem here, such as configuration specifics, network conditions, data volumes, etc.

**Comment by nickscamara** [comment]
Thanks @ysijason, looking into it!

**Comment by nickscamara** [comment]
Fixed!
