### ISSUE TITLE
[Feat] Remove cookie banner/pop up from screenshots

### ISSUE THREAD

**Issue by ifx-querido** [mendableai/firecrawl#647]
**Problem Description**
When taking a full screenshot, the cookie banner / privacy settings pop up hides a significant portion of the image.

**Proposed Feature**
It would be very handful if any and every irrelevant pop up could be blocked so they don't appear on the screenshot, hiding important content from the user.

**Alternatives Considered**
The only alternatives I'm aware of are outside of the Firecrawler scope, and involve driver automation, through selenium for example.

**Implementation Suggestions**
Using some kind of cookie blocker addon might work, assuming the firecrawler incorporates driver automation.

**Use Case**
This feature can be seen as an improvement of the full page screenshot format that already exists.  A clean not obstructed screenshot could be used to visually validate the extracted text content, and could also be used for some kind of AI image classification.

**Additional Context**
There are browser addons for taking full page screenshots, but not on an automated way.

**Comment by tomkosm** [comment]
Hey @tomkosm , we already support this at the cloud version and it will soon be opensource. Are you trying self hosted or via the cloud? If its via the cloud could you provide the link to have a look?

**Comment by ifx-querido** [comment]
Hello @tomkosm , I'm not trying self hosted yet but soon will be. For now I'm just experimenting with the Python SDK using an API key with the free plan.

This is the code I'm running:
```
page_content = app.scrape_url(website, {
  "formats": ['markdown', 'links', 'screenshot@fullPage'],
  "onlyMainContent": True,
})
print(page_content['screenshot'])
```

And the output screenshot that shows the cookie pop up can be found [here](https://alttmdsdujxrfnakrkyi.supabase.co/storage/v1/object/public/media/screenshot-1732761.png)

**Comment by ifx-querido** [comment]
any help would be appreciated @tomkosm @kevinswiber

**Comment by nickscamara** [comment]
Hey @ifx-querido, it is fixed! https://service.firecrawl.dev/storage/v1/object/public/media/screenshot-c0372c61-1b4c-4027-9c92-020fd4afaa08.png
