### ISSUE TITLE
[BUG] On free plan, customer getting hit with Insufficient credits after

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#651]
Issue with payment - customer says they only used 16 credits

<img width="415" alt="image" src="https://github.com/user-attachments/assets/39442510-cfb2-4568-a093-108510a2cbb7">

**Comment by ifx-querido** [comment]
I've had this issue as well. My belief is you've probably tried to scrape/crawl too often. Remember that on the free plan you can only make 10 scrape requests per min, and 1 crawl request per minute. Just wait for a while and try again to see if the error reappears.
