### ISSUE TITLE
demo is broken SyntaxError: The requested module '@mendable/firecrawl-js' does not provide an export named 'JobStatusResponse'

### ISSUE THREAD

**Issue by AlexanderKozhevin** [mendableai/firecrawl#657]
**Describe the Bug**
Used demo from landing page

**To Reproduce**
```
// npm install @mendable/firecrawl-js
import FirecrawlApp, { JobStatusResponse } from '@mendable/firecrawl-js';

const app = new FirecrawlApp({apiKey: "fc-8fd17.......fd"});

// Scrape a website:
const scrapeResult = await app.scrapeUrl('firecrawl.dev');

console.log(scrapeResult.data.markdown)
```

**Expected Behavior**
GET MD text

SyntaxError: The requested module '@mendable/firecrawl-js' does not provide an export named 'JobStatusResponse'

**Comment by mogery** [comment]
Hi there, are you using TypeScript or plain JavaScript? This example code is meant for TypeScript users. `JobStatusResponse` is a type we export.

**Comment by mogery** [comment]
Also, that bit of code is not on our landing page anymore.
![image](https://github.com/user-attachments/assets/22de87c3-2e62-4bc9-9dcc-94d8937019b7)
