### ISSUE TITLE
[py-sdk] Not returning rawHTML (?)

### ISSUE THREAD

**Issue by khemiri-mohamed** [mendableai/firecrawl#661]
from firecrawl import FirecrawlApp

app = FirecrawlApp(api_key="fc-bfd[REDACTED]")

# Scrape a website:
scrape_result = app.scrape_url('firecrawl.dev', params={'formats': ['rawHtml']})
print(scrape_result)

this doesn't return raw html instead it return markdown data, we need just the html

**Comment by nickscamara** [comment]
Hey @khemiri-mohamed I would recommend revoking your API key as it was exposed above. We're looking into the issue. Which version of the python sdk are you using? Thanks!

**Comment by nickscamara** [comment]
Make sure you are using version 1.2.3 on the Python SDK.

**Comment by khemiri-mohamed** [comment]
yep fixed thanks !
