### ISSUE TITLE
[Self-Host] not getting any information on succesfull scrape request

### ISSUE THREAD

**Issue by yashsharma999** [mendableai/firecrawl#666]
I've set up the project locally, on making a succesfull `/POST http://localhost:3002/v0/scrape` request, not really getting any information. Am i missing something ?

**Screenshots**
<img width="844" alt="Screenshot 2024-09-15 at 10 19 09 AM" src="https://github.com/user-attachments/assets/364209bd-760d-4276-b9bb-68158329186f">

**Comment by mogery** [comment]
Hi there, please try this using the v1 API.

**Comment by yuanzhiwei** [comment]
![image](https://github.com/user-attachments/assets/c6a24190-5353-4517-95c3-ec751a684579)

same question, what can i fix it?

**Comment by rafaelsideguide** [comment]
Hey @yashsharma999 and @yuanzhiwei, we've made several improvements to our self-host codebase. Could you please update your local repository and give it another try? Additionally, feel free to check out the [self-host guide](https://docs.firecrawl.dev/contributing/self-host) for further assistance. Let me know how it goes!
