### ISSUE TITLE
[DX] Breaking type change in latest node SDK release

### ISSUE THREAD

**Issue by OliverWales** [mendableai/firecrawl#675]
A recent change to the NodeJS SDK adds a required type parameter to ScrapeResponse meaning you are now required to write `ScrapeResponse<undefined>` even if you're not using the LLM functionality. It would be nicer DX (and not a breaking change) if this type parameter was defaulted to e.g. `undefined`, `unknown` or `{}`/`object`.

This change appears to have been added in:
https://github.com/mendableai/firecrawl/commit/a2903e75cfb06fa7cbbb31e663908c70c42a544d
CC @mogery 

**Environment (please complete the following information):**
- OS: macOS
- Firecrawl Version: 1.4.3
- Node.js Version: 22

**Comment by mogery** [comment]
Thanks for reporting, this should be solved in b2b7f8d87495847335321a5e63e2186c13dc6cf0. Waiting for a publish @nickscamara @rafaelsideguide

**Comment by nickscamara** [comment]
Published a few hours ago!

**Comment by mogery** [comment]
Live on version `1.4.5`
