### ISSUE TITLE
[Bug] Module '"cheerio"' has no exported member 'AnyNode'

### ISSUE THREAD

**Issue by yuanzhiwei** [mendableai/firecrawl#681]
**Describe the Bug**
node: v20.17.0
pnpm: 9.10.0
cheerio: 1.0.0
firecrawl:  clone master

Start firecrawl locally, pnpm install is down, after pnpm run workers and pnpm run start, a while later the following error will be reported, and the test example cannot be accessed

![image](https://github.com/user-attachments/assets/c7d06f85-cd82-4719-9dd5-1f1aff4c75c3)

![image](https://github.com/user-attachments/assets/f3754fc6-3cae-4404-9a7b-3ff41fef0962)

**Comment by kk-fan** [comment]
I have also encountered this problem. Is there a solution?

**Comment by L1aoxw** [comment]
You can try changing the version of cheerio from 1.0.0 to 1.0.0-rc.12
`npm install cheerio@1.0.0-rc.12`

**Comment by kk-fan** [comment]
> You can try changing the version of cheerio from 1.0.0 to 1.0.0-rc.12您可以尝试将 cheerio 的版本从 1.0.0 更改为 1.0.0-rc.12 `npm install cheerio@1.0.0-rc.12`

开始使用yarn，换成pnpm解决，感谢。

**Comment by rafaelsideguide** [comment]
Using `pnpm` solves the problem. Closing for now. Feel free to reopen the issue if you continue to experience this problems.

**Comment by aar2dee2** [comment]
For anyone running into this, use pnpm version `9.12.2`

**Comment by swyxio** [comment]
recorded my guide here getting this running in case it helps someone https://youtu.be/LHqg5QNI4UY

**Comment by mehrdad-shokri** [comment]
Looking at [cheerio source code](https://github.com/cheeriojs/cheerio/blob/b8da06df02d65be29eea250fb0bb362ce6962dc9/src/load-parse.ts#L32) `AnyNode` is still used as input type for `load`. I guess in it's newer version, they don't reexport it from `domhandler`. you can replace import `AnyNode` to directly from `domhandler` in your code with 
```typescript
import type {AnyNode} from 'domhandler';

```
