### ISSUE TITLE
[Self-Host] use v1/scrape not getting any information on successful

### ISSUE THREAD

**Issue by yuanzhiwei** [mendableai/firecrawl#684]
request successful and no page content return~ 

![image](https://github.com/user-attachments/assets/bdcd18b0-0ee9-41b5-b376-704546a954ae)

**Comment by joshua-mo-143** [comment]
Looks fine to me:
![image](https://github.com/user-attachments/assets/160ae762-23e1-468c-a80f-b911c91be4a4)

Can you include some steps for reproduction?

**Comment by yuanzhiwei** [comment]
> Looks fine to me (if you do it from the playground): ![image](https://private-user-images.githubusercontent.com/102877324/370271677-160ae762-23e1-468c-a80f-b911c91be4a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NTg2MzIsIm5iZiI6MTcyNzY1ODMzMiwicGF0aCI6Ii8xMDI4NzczMjQvMzcwMjcxNjc3LTE2MGFlNzYyLTIzZTEtNDY4Yy1hODBmLWI5MTFjOTFiZTRhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwMTA1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWJhZWQ4OTAxN2ZiYzdkZjk0OGRkOWMxN2M5YzFjOGE4ZWQ4YmM4NTkxMDFhOTQyOGRmZWYyZTg5MTU5MzllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.F909z62bxjVcdg8434TmcIzEplc7Om5j8Rl0i2kUBpo)
> 
> Can you include some steps for reproduction?

just execute [pnpm run workers] and [pnpm run start],  no error report,  then request in postman,  no markdown result.

**Comment by a327958099** [comment]
Encountered the same problem

**Comment by mogery** [comment]
QQ blocks fetch-based requests. For self-host you will need to set up the Playwright microservice.
