### ISSUE TITLE
[Feat] Improve Rust SDK

### ISSUE THREAD

**Issue by joshua-mo-143** [mendableai/firecrawl#687]
**Problem Description**
There are some areas for improvement in the Rust SDK.

A couple of the most egregious that stand out to me:
- We should be using structs that implement (de)Serialize instead of trying to use the `json!` macro everywhere (and we can use traits like `Into<T>` and `From<T>` to make this much, **much** easier for users)
- We should be using enums to illustrate a finite number of variants (because as far as I know, there's only a finite amount of variants that formats can cover)

I'd be happy to volunteer the relevant code amendments myself, as most of them are quite easy to implement (relatively speaking).

**Proposed Feature**
Adding more idiomatic Rust conventions to the SDK (like using builders, making it more convenient for users to use the API, etc...)

**Alternatives Considered**
I guess the alternative here would be to just not carry out the changes, if there isn't enough time for the Firecrawl team to scope out change reviews.

**Implementation Suggestions**
For example, instead of using the JSON macro we could have:
```rust
#[derive(Debug, Serialize, Deserialize, Clone)]
struct ScrapeParams {
    formats: Vec<Format>,
    // ... etc
}

impl Default for ScrapeParams {
   // .. set defaults here, if we need it
}

#[derive(Debug, Serialize, Deserialize, Clone)]
enum Format {
    Markdown,
    Html
}

impl Display for Format {
    fn display(&self, f: &mut Formatter<'_>) -> fmt::Display {
        match self {
            Self::Markdown => write!(f, "markdown"),
            Self::Html => write!(f, "html"),
        }
    }
}

impl From<Format> for ScrapeParams {
     fn from(format: Format) -> Self {
          Self { formats: Vec![format] }
     }
}

// example of re-adjusted crawl function below
// not sure the generics are entirely correct for the AsRef, but this can be amended in-code
fn scrape_url<P: Into<CrawlParams>, S: AsRef<&str>>(url: S, params: P) {
    // the rest of the thing here and whatnot
}
```

This would then be something like this in practical usage:

```rust
    firecrawl_client.scrape_url("firecrawl.dev", Format::Markdown);
```

**Use Case**
Makes things much easier DX-wise by not having to constantly look back at the SDK to figure out what parameters are available - users can instead use LSP autocompletion, which will greatly enhance the possible Rust dev experience with Firecrawl.

**Additional Context**
Not really any other additional context to add.

Let me know your thoughts!

**Comment by mogery** [comment]
hell yeah! i'll jump on this later

**Comment by mogery** [comment]
Hey Joshua, I've started updating the codebase for v1 in #689. I'd love to hear your thoughts on the direction I'm heading in.

**Comment by joshua-mo-143** [comment]
Looks good to me.

I'm definitely more of a fan of builder methods, but this isn't my API so I have no argument there.

**Comment by mogery** [comment]
Docs merge and cargo publish pending, good to go otherwise.

**Comment by mogery** [comment]
[It's up!](https://crates.io/crates/firecrawl/1.0.0)

**Comment by mogery** [comment]
We'll also be looking into adding builders as an alternative to the `Default::default()` syntax at a later date.
