### ISSUE TITLE
ext-integrations: /search support on Langchain

### ISSUE THREAD

**Issue by nickscamara** [mendableai/firecrawl#70]

**Comment by rafaelsideguide** [comment]
python: https://github.com/langchain-ai/langchain/pull/21782
js/ts: https://github.com/langchain-ai/langchainjs/pull/5418

waiting review

**Comment by rafaelsideguide** [comment]
Changes requested. I did the commit with the changes. Waiting for review.

**Comment by rafaelsideguide** [comment]
Search was deprecated in v1. Closing this for now.
