### ISSUE TITLE
[Bug] Pressing Enter doesn't work in Actions

### ISSUE THREAD

**Issue by trancethehuman** [mendableai/firecrawl#705]
**Describe the Bug**
When running a scrape that has actions, an Enter key action after typing out in search input doesn't do anything for sites like Amazon, Meetup and Eventbrite. A click action on the search button worked though.

**To Reproduce**

```python
test_scrape_amazon = app.scrape_url(test_site["url"], 
    params={
        'formats': ['markdown', 'html'], 
        'actions': [
            {"type": "wait", "milliseconds": 1120},
            {"type": "click", "selector": test_site["search_input"]},
            {"type": "wait", "milliseconds": 1114},
            {"type": "write", "text": "aprons"},
            {"type": "wait", "milliseconds": 1000},
            {"type": "press", "key": "ENTER"},
             {"type": "wait", "milliseconds": 1124},
            {"type": "screenshot"}
        ]
    }
)
```

The screenshot that came back is still the home page. But replacing the Enter key with a click on the search button worked.

**Comment by nickscamara** [comment]
Thanks for reporting! Ccing @tomkosm here to take a look and get it fixed!

**Comment by tomkosm** [comment]
Hey @trancethehuman , can you provide the url so I can try to replicate?

**Comment by trancethehuman** [comment]
@tomkosm amazon.ca, meetup.com, perplexity.ai

**Comment by tomkosm** [comment]
@trancethehuman sorry for the trouble, just fixed this bug. The fix should be up in a few minutes, let us know if its not solved or you face any other issues.
