### ISSUE TITLE
[Bug] Getting 500 internal server error frequently when using format = screenshot

### ISSUE THREAD

**Issue by ericciarla** [mendableai/firecrawl#709]
I am trying to get screenshots for websites with the JS SDK like this:
  `const app = new FirecrawlApp({ apiKey: process.env.FIRECRAWL_API_KEY });
const scrapeResponse = await app.scrapeUrl(url, {
      formats: [ "screenshot" ],
    });`

and I am frequently getting responses like these back:

`{
  success: true,
  warning: undefined,
  error: undefined,
  metadata: {
    sourceURL: ‘https://www.firecrawl.dev/’,
    sitemap: { changefreq: ‘weekly’, lastmod: ‘2024-09-25T03:18:47.232Z’ },
    error: ‘INTERNAL SERVER ERROR’,
    statusCode: 500
  }
}`

when I change the request to this it seems to work better:
`const scrapeResponse = await app.scrapeUrl(url, {
      formats: [ "rawHtml","screenshot" ],
    });`

**Comment by nickscamara** [comment]
Fixed!
