### ISSUE TITLE
[Bug] 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by bytrangle** [mendableai/firecrawl#720]
**Describe the Bug**
When crawling a website with FireCrawlLoader, I got an error:
 > AttributeError: 'str' object has no attribute 'get'

**To Reproduce**
The full code:

```
from langchain_community.document_loaders import FireCrawlLoader

url="https://firecrawl.dev"
loader = FireCrawlLoader(
  api_key="VALID_API_KEY",
  url=url,
  mode="crawl",
)
docs = loader.load()
```
According to the activity log, the crawling job was a success.

Is it possibly a bug from is the relevant code from Langchain's [document loader]((https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/document_loaders/firecrawl.py#L108)) for FireCrawl:

**Screenshot**
![Screenshot from 2024-09-30 17-19-21](https://github.com/user-attachments/assets/e3d8be07-6b54-4ba3-a469-4f46bcc6f768)

**Environment (please complete the following information):**
- OS: Linux
- Firecrawl Version: [e.g. 1.2.3]

**Comment by nickscamara** [comment]
@bytrangle we're waiting for them to merge the fix https://github.com/langchain-ai/langchain/pull/26548

**Comment by bytrangle** [comment]
@nickscamara Thank you for the heads up. While waiting, is there anything I can do to get around this? A simple script like this will fail in the meantime:

```
from langchain_community.document_loaders import FireCrawlLoader

loader = FireCrawlLoader(
  url="https://firecrawl.dev",
  mode="crawl",
)

docs = loader.load()
docs[0]
```

**Comment by rafaelsideguide** [comment]
@bytrangle, as a workaround, you can install version 0.0.20 of the SDK with `pip install --force-reinstall "firecrawl-py==0.0.20"`
