### ISSUE TITLE
[Bug] Python SDK: Crawl Job Failed or Was Stopped but It Was Actually a Success

### ISSUE THREAD

**Issue by bytrangle** [mendableai/firecrawl#729]
**Describe the Bug**
I'm using FireCrawlLoader integration with Langchain to crawl a website.

**To Reproduce**
Steps to reproduce the issue:
1. Install `langchain_community.document_loaders"
2. Set envrionment variable FIRECRAWL_API_KEY
3. Instantiate a crawl job:
```
from langchain_community.document_loaders import FireCrawlLoader

loader = FireCrawlLoader(
  url="https://firecrawl.dev",
  mode="crawl",
)

docs = loader.load()
docs[0]
```
4. Run the Python script.
5. See the error in the console

> Exception: Crawl job failed or was stopped. Status: failed

**Expected Behavior**
The crawl job was a success according to the Activity Logs in FireCrawl dashboard. 

Running the script above should print a Document with metadata that includes properties like `ogUrl`, `sourceUrl`, `keywords`.

I'm not sure if the error is due to FireCrawl integration with Langchain or FireCrawl's Python SDK, but the error can be traced to the function [monitor_job_status](https://github.com/mendableai/firecrawl/blob/main/apps/python-sdk/firecrawl/firecrawl.py#L325) in the file `firecrawl.py` of Python SDK.

This function is only called when response's status code is 200. The function raises an exception when `status_data['status']` is not one of the following: completed, active, paused, pending, queued, waiting, scraping.

So what exactly is the value of `status_data['status']`? Anyway, `monitor_job_status` shouldn't throw a "crawl job failed" error when it was in fact successful.

**Screenshots**
The full traceback:

![Screenshot from 2024-10-03 17-04-14](https://github.com/user-attachments/assets/07ffcc5a-a957-4515-a73b-7438564b505d)

**Environment (please complete the following information):**
- OS: [Linux]
- Firecrawl Version: [e.g. 1.2.3]

**Comment by nickscamara** [comment]
@bytrangle we're looking into it!

**Comment by nickscamara** [comment]
Fixed!!
