### ISSUE TITLE
ModuleNotFoundError: No module named 'firecrawl'

### ISSUE THREAD

**Issue by faddy19** [mendableai/firecrawl#74]
I do pip install firecrawl-py

I cannot run the crawler. I get this when installing the SDK

WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/packaging-24.0.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/packaging-24.0.dist-info due to invalid metadata entry 'name'
Requirement already satisfied: firecrawl-py in /opt/homebrew/lib/python3.11/site-packages (0.0.6)
Requirement already satisfied: requests in /opt/homebrew/lib/python3.11/site-packages (from firecrawl-py) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/lib/python3.11/site-packages (from requests->firecrawl-py) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.11/site-packages (from requests->firecrawl-py) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/lib/python3.11/site-packages (from requests->firecrawl-py) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.11/site-packages (from requests->firecrawl-py) (2024.2.2)
WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/packaging-24.0.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/packaging-24.0.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/packaging-24.0.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/packaging-24.0.dist-info due to invalid metadata entry 'name'

After that when I run the file, it gives back:

 from firecrawl import FirecrawlApp
ModuleNotFoundError: No module named 'firecrawl'

**Comment by faddy19** [comment]
Any idea?

**Comment by rafaelsideguide** [comment]
Hey @faddy19! I just tested the package and it seems to be working well.
I think your problem is related your Python environment, specifically with the packaging module in your Python installation. 

Try to reinstall the `packaging` module with:
`pip install --upgrade --force-reinstall packaging`

Them reinstall the firecrawl-py:
`pip install --upgrade --force-reinstall firecrawl-py`

**Comment by faddy19** [comment]
Will check that Rafael. Amazing support by the way. One more question: 

What happens if the websites have a captcha or cloudflare bot detection. Does it still work?

Second: how fast is it compared to Apify

Thank you

**Comment by nickscamara** [comment]
@faddy19 Hi! 1. Yes, it should still work. Although it vary depending on the website, so I would do some testing beforehand. And 2. https://twitter.com/AlexReibman/status/1780299595484131836

Thank you! Let us know if you have any more questions!
