### ISSUE TITLE
[Bug] excludePaths format isn't documented anywhere

### ISSUE THREAD

**Issue by mdagost** [mendableai/firecrawl#764]
**Describe the Bug**
Provide a clear and concise description of what the bug is.

I'm having trouble using excludePaths because I can't find documentation anywhere on how it works.  Is it a regex?  Is it a glob pattern?  What is it?

**Comment by rafaelsideguide** [comment]
Hey @mdagost , I just PR'd a better description for `includePaths` and `excludePaths` to our docs. This is how it works:

`excludePaths` (`string[]`): Specifies URL patterns to exclude from the crawl by comparing website paths against the provided regex patterns. For example, if you set `"excludePaths": ["blog/*"]` for the base URL `firecrawl.dev`, any results matching that pattern will be excluded, such as `https://www.firecrawl.dev/blog/firecrawl-launch-week-1-recap`.

**Comment by nickscamara** [comment]
It follows glob pattern!

**Comment by mdagost** [comment]
Which is it?  regex or glob pattern?

**Comment by mdagost** [comment]
I've seen both referenced.  When I try glob patterns that involve the `**` pattern I get an error about a regex, which made me think that it's actually a regex.
