### ISSUE TITLE
[Feat] Provide more details for 429 Rate limit reached

### ISSUE THREAD

**Issue by tractorjuice** [mendableai/firecrawl#81]
Other APIs provide details within the 429 response that enables a calculation or even the details of when to retry.
For example:

Groq:

Error: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama3-70b-8192` in organization `org_xxxxxxx` on tokens per minute (TPM): Limit 7000, Used 0, Requested ~12903. Please try again in 50.597142857s. Visit https://console.groq.com/docs/rate-limits for more information.', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

**Comment by nickscamara** [comment]
Great idea.

**Comment by simonha9** [comment]
Would love to take this

**Comment by nickscamara** [comment]
@simonha9 Yey! Go for it! Yep, so we should be pushing this week/next week a more strict enforcement on the rate limit based on the subscription. Right now crawlStatus is the only one that differs outside of the preview ones/ server ones.

**Comment by simonha9** [comment]
Sounds good! Please link a wiki or update this thread when you have an idea what the rate limits should be per subscription + if you have any specific verbiage in mind for the rate limit error messages and I can go ahead an implement this.

**Comment by rafaelsideguide** [comment]
@simonha9 we've already implemented the rate limits as detailed in issue #151 . You can proceed with implementing the additional details for the 429 rate limit responses as discussed. Looking forward to seeing your contributions!

**Comment by simonha9** [comment]
Thanks for implementing the rate limits, I will start on this today 😄
