### ISSUE TITLE
[Bug/Investigation] Some relative paths are incomplete

### ISSUE THREAD

**Issue by rafaelsideguide** [mendableai/firecrawl#821]
When crawling https://docs.cleanlab.ai, it looks like the URLs are incomplete. For example, this URL in the response:
https://docs.cleanlab.ai/cleanlab/token_classification/index.html
is indeed a 404 page, but it should actually be:
https://docs.cleanlab.ai/stable/cleanlab/token_classification/index.html.

This issue seems to occur because the elements on the page use relative paths like `<a class="reference internal" href="../../tutorials/token_classification.html">Token Classification (text)</a>`.

**Comment by rafaelsideguide** [comment]
Found it. If the page get's redirected, firecrawl still uses the baseURL to create the links to be crawled. Need to update for these cases.

**Comment by nickscamara** [comment]
@mogery observe if the url redirects, if it doesnt cancel scrapes and redo it with the new base URL.
