### ISSUE TITLE
[Feat] Error handling middleware for the API

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#87]
When errors occur in deeply nested functions, there isn't a way for us to bubble up custom error messages and codes to the API layer. 

Proposal: Create a custom Error type and Middleware that intercepts errors. 

Middleware example

```typescript

class AppError extends Error {
  public readonly statusCode: number;
  public readonly isOperational: boolean;

  constructor(message: string, statusCode: number, isOperational: boolean = true) {
    super(message);
    this.statusCode = statusCode;
    this.isOperational = isOperational; // Indicates this is a known type of error
    Object.setPrototypeOf(this, new.target.prototype); // restore prototype chain
    Error.captureStackTrace(this, this.constructor);
  }
}
```

Deep function:

```typescript
async function someDeepFunction(): Promise<any> {
  try {
    // Some logic that might fail
    if (someConditionNotMet) {
      throw new AppError('Specific error message', 404);
    }
    // more logic
  } catch (error) {
    throw new AppError('Error accessing resource', 500);
  }
}
```

Then these errors would be intercepted and cleaned for users by a middleware at the express level.

**Comment by rafaelsideguide** [comment]
This feature request has been inactive for 28 days and was not prioritized. I'm closing it for now. If this feature becomes a priority in the future, please feel free to reopen or submit a new request.
