### ISSUE TITLE
[Self-Host] crawl job can't stop

### ISSUE THREAD

**Issue by TChengZ** [mendableai/firecrawl#874]
**Describe the Issue**
Provide a clear and concise description of the self-hosting issue you're experiencing.

**To Reproduce**
Steps to reproduce the issue:
1、i self-host the firecrawl and crawl website 'https://www.16888.com' with crawl params
![image](https://github.com/user-attachments/assets/ac224a92-67d2-4f2e-8f87-22ba7d841b28)
but the job seems to be endless until the OOM happens to redis and the app crash
![image](https://github.com/user-attachments/assets/5db14467-2750-4fc3-aa4c-0afd66e9e1e9)
![image](https://github.com/user-attachments/assets/77beb1be-f72e-4a70-92e6-35c71336f0e0)

2、then i change the way using firecrawl with api-key, crawl the same  website 'https://www.16888.com' with same crawl params,
then everything goes well,it crawl only 10 pages
![image](https://github.com/user-attachments/assets/585eee87-7557-4ced-9d58-e7a188016fba)

i think there must have some bug in open-source firecrawl

**Expected Behavior**
A clear and concise description of what you expected to happen when self-hosting.

**Screenshots**
If applicable, add screenshots or copies of the command line output to help explain the self-hosting issue.

**Environment (please complete the following information):**
- OS: linux
- Firecrawl Version: main branch last commit time:Mon Oct 28 20:28:30 2024 -0300
- Node.js Version: 20.11.1

**Logs**
If applicable, include detailed logs to help understand the self-hosting problem.

**Configuration**
Provide relevant parts of your configuration files (with sensitive information redacted).

**Additional Context**
Add any other context about the self-hosting issue here, such as specific infrastructure details, network setup, or any modifications made to the original Firecrawl setup.

**Comment by mogery** [comment]
Hi there. We've had issues with the `limit` parameter. Looking into this.

**Comment by TChengZ** [comment]
> Hi there. We've had issues with the `limit` parameter. Looking into this.

which?

**Comment by TChengZ** [comment]
fixed
