### ISSUE TITLE
[Feat] Status report of failed pages on crawl endpoint

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#88]
Implement an API endpoint to return status reports detailing which pages failed and the reasons for these failures.

Output: The API should return a concise log of failed pages, including error codes and brief descriptions.

Requested by info@matebela.com

**Comment by nickscamara** [comment]
Once we figure out a "smarter" way to detect why it wasn't able to properly scrape, this should get-reprioritized

**Comment by rafaelsideguide** [comment]
@nickscamara @calebpeffer Is this one closed by #276 ?

**Comment by rafaelsideguide** [comment]
Closing this one.
