### ISSUE TITLE
[Bug - Actions] All scraping engines failed!

### ISSUE THREAD

**Issue by yupingsong-anylink-io** [mendableai/firecrawl#884]
**Describe the Bug**
When using FirecrawlApp.app.scrape_url to scrape a page, the following error is received:
`Error: Internal Server Error: Failed to scrape URL. (Internal server error) - All scraping engines failed! - No additional error details provided.`
The same code used to work properly.

**Screenshots**

**Environment (please complete the following information):**
- OS: Windows
- Firecrawl Version:1.3.1
- python Version: 3.10

**Logs**
```
Scrape {my url} failed. Error: Internal Server Error: Failed to scrape URL. (Internal server error) - All scraping engines failed! - No additional error details provided.
```

**Additional Context**
```py
crawler = FirecrawlApp(api_key=os.getenv("FIRECRAWL_API_KEY"))


class ExtractSchema(BaseModel):
    urls: List[str]


def search_by_keyword(search_url: str, key_word: str) -> str:
    print(f"Starting search with keyword: {key_word}")
    try:
        scrape_result = crawler.scrape_url(
            search_url,
            params={
                "formats": ["extract"],
                #Specify the HTML tags, classes and ids to include in the response.
                "includeTags": ["#t table.eps-table td.views-field-dummy-notice-title a"],
                #A prompt for the LLM to extract the data in the correct structure.
                "extract": {
                    "prompt": "Extract the url of <a> element",
                    "schema": ExtractSchema.model_json_schema()
                },
                "actions": [
                    {"type": "wait", "milliseconds": 2000},
                    {"type": "click", "selector": "#edit-words--7"},
                    {"type": "wait", "milliseconds": 500},
                    {"type": "write", "text": key_word},
                    {"type": "wait", "milliseconds": 500},
                    {"type": "press", "key": "Enter"},
                    {"type": "wait", "milliseconds": 8000}
                ]
            }
        )
        print("Search completed. Processing results...")
        return json.dumps(scrape_result)
    except Exception as e:
        print(f"Scrape {search_url} failed. Error: {e}")
        return ""
```

**Comment by longmans** [comment]
Me, too

**Comment by mogery** [comment]
Can you please share an example URL where this fails?

**Comment by mogery** [comment]
I believe this may be fixed by f097cdd, but it is hard to debug without a URL.

**Comment by yupingsong-anylink-io** [comment]
The `search_url` is `https://canadabuys.canada.ca/en/tender-opportunities?search_filter=&status%5B87%5D=87&status%5B1920%5D=1920&pub%5B3%5D=3&record_per_page=50&current_tab=t&words=`,  and `key_word` is `Walkway`

**Comment by mogery** [comment]
Hi there, I cannot recreate the issue anymore. Is it fixed for you as well?

**Comment by yupingsong-anylink-io** [comment]
I just confirmed, it's fixed on my end too, thanks!

Is there any repair done on the firecrawl server side? Or is it due to my local reasons? If this problem recurs in the future, it will be easier for me to locate it.

**Comment by mogery** [comment]
This was repaired server-side, in commit f097cdd. We weren't accounting for the wait actions in our timeout logic.

**Comment by aakriti-14** [comment]
I am also facing this similar issue. I am providing these actions. 
```
actions = [
      {"type": "wait", "milliseconds": 2000},  # Wait before clicking
      {"type": "click", "selector": 'button[data-v-257ec5c0]'},  # Click the "Show More" button
      ...
      (repeated 50 times)
      {"type": "scrape"}
    ]
```
I am using the timeout of > 10 mins as well. Can you please help here @mogery ?

**Comment by nickscamara** [comment]
Hey yall, we finally were able to fix this hairy bug! 

@longmans @yupingsong-anylink-io @aakriti-14

**Comment by ER-EPR** [comment]
I think it happens again
