### ISSUE TITLE
[Self-Host] Is it possible to resolve local html files?

### ISSUE THREAD

**Issue by Taimin** [mendableai/firecrawl#896]
**Describe the Issue**
I have already downloaded multiple html files. When I try to use a local firecrawl to transform these files into markdown, I got an empty dictionary in 'data'.

**To Reproduce**
```
app = FirecrawlApp(api_key="1", api_url="http://localhost:3002/")

crawl_status = app.crawl_url(
  local_html_file_path, 
  params={
    'scrapeOptions': {'formats': ['rawHtml', ]}
  }
)
print(crawl_status)
```

**Expected Behavior**
The whole html file should be converted to a markdown file.

**Screenshots**
![image](https://github.com/user-attachments/assets/9ef1f37a-8125-4c61-9fea-38eae37b895d)
The data is empty.

**Comment by hemeda3** [comment]
UP!
same here, but iam using the cloud api, 
I have the files locally, dont want to upload them publicly,  want to send file from local to firecrawl server  from my laptop

**Comment by mogery** [comment]
You can do this by hosting the file locally, with python for example:
`python3 -m http.server`

After that, you can point your crawl at `http://localhost:8000/<file path relative to the directory you started the server in>`

**Comment by mogery** [comment]
> UP! same here, but iam using the cloud api, I have the files locally, dont want to upload them publicly, want to send file from local to firecrawl server from my laptop

We do not support this.

**Comment by hemeda3** [comment]
@mogery  yes I am aware of this, just wanted to find a trick helping me avoid uplading my private files publicly, at the same time using your cloud API

> You can do this by hosting the file locally, with python for example: `python3 -m http.server`
> 
> After that, you can point your crawl at `http://localhost:8000/<file path relative to the directory you started the server in>`

Thanks, this is super helpful

**Comment by Tavish9** [comment]
Hi, @mogery, @Taimin  I start my firecrawl in docker, it works fine when scraping public url.

However, when i start a http server locally and pass the url to my firecrawl, it raises an error:
```bash
requests.exceptions.HTTPError: Unexpected error during scrape URL: Status code 400. Bad Request - [{'code': 'custom', 'm
essage': 'Invalid URL', 'path': ['url']}]
```

I am sure that the url is correct(`http://localhost:8000/my_file`), as i can open it in my browser. 

Any ideas?

**Comment by mogery** [comment]
You'll have to specify an IP or a valid domain (`127.0.0.1`) instead of `localhost`

**Comment by Tavish9** [comment]
Thanks for reply. However, it still raises an error

```bash
requests.exceptions.HTTPError: Internal Server Error: Failed to scrape URL. (Internal server error) - All scraping engin
es failed! -- Double check the URL to make sure it's not broken. If the issue persists, contact us at help@firecrawl.com
. - No additional error details provided.
```

**Comment by Zhaolun-Liu** [comment]
This because you are attempting to connecting to an ip address classified as private. The "makeSecureDispatcher" function in apps/api/src/scraper/scrapeURL/engines/utils/safeFetch.ts includes a security check that destroys the connection if it detects a private IP address, which is considered in secure. You can adjust "isIPv4Private" to allow specific private address.
