### ISSUE TITLE
[Bug] Typo in Crawl docs

### ISSUE THREAD

**Issue by alexander-zuev** [mendableai/firecrawl#917]
**Describe the Bug**
 There is a mismatch in the default value of `limit` parameter (see screenshot):

![Screenshot 2024-11-22 at 7 11 30 AM](https://github.com/user-attachments/assets/28a4f0c9-6220-443d-938b-8896ca5e1d77)

**Comment by nickscamara** [comment]
Thank you @alexander-zuev! Just fixed!
