### ISSUE TITLE
[Self-Host] /crawl Request failed

### ISSUE THREAD

**Issue by Highlighz** [mendableai/firecrawl#945]
**/scrape and /map Can request normally：**
**/scrape**
![scrape测试](https://github.com/user-attachments/assets/f1c8c4fe-ab66-4da5-aca1-be8d00ea91c9)

**/map**
![map测试](https://github.com/user-attachments/assets/a4ac2071-ee1a-48bd-8ad9-1902abc6a040)

**An error is reported using /crawl**
![crawl](https://github.com/user-attachments/assets/ff5cbc3c-699a-4430-9147-8f596758099b)

**error**
![error](https://github.com/user-attachments/assets/29683bc4-3f56-46f2-9fc6-b318cc81aab9)

**Comment by nickscamara** [comment]
@Highlighz are there more logs you can provide to us? ccing @mogery here to take a look.

**Comment by Highlighz** [comment]
**Initialized**
![initialized](https://github.com/user-attachments/assets/94a21fc0-6d2e-44cf-8780-21fad82a023b)

*Visit https://dig.watch/*

**After running scrape**
![scrape后](https://github.com/user-attachments/assets/dc47e4e1-89d2-441c-b8ba-9c5a6a3117ce)

**After running map**
![使用map后start](https://github.com/user-attachments/assets/fe224bc8-964a-4ffa-a25f-4c8f152b0536)

**After running crawl**
![crawl报错](https://github.com/user-attachments/assets/5d94deb8-8c38-4eda-a0d8-65dc1943ee6f)


> @Highlighz are there more logs you can provide to us? ccing @mogery here to take a look.

**Comment by Highlighz** [comment]
![image](https://github.com/user-attachments/assets/01530f74-daa1-41aa-89ee-d628c0fcd54a)

**Comment by Highlighz** [comment]
Issue resolved, redis version issue (>=7)

**Comment by Highlighz** [comment]
Issue resolved, redis version issue (>=7)
