### ISSUE TITLE
[Self-Host] Python sdk requires api key

### ISSUE THREAD

**Issue by antongisli** [mendableai/firecrawl#947]
**Describe the Issue**
I can't use the python sdk as it asks for an api key. But I don't have an api key for self hosting.

**To Reproduce**
Steps to reproduce the issue:
Try to use Python sdk with self hosting with no api key

**Expected Behavior**
API key should be optional

Basically I had to hack the fire crawl SDK library to remove the check for API key parameter and modify the api calls / remove the auth header. 

Am I doing something wrong or do you really require api key for sdk for some reason?

**Comment by ruspaul013** [comment]
Hello @antongisli!

I had the same problem while using the go sdk, but if you give any value to the api key variable should be ok.
```
apiKey = "changeme"
```

**Comment by antongisli** [comment]
Hmm I thought I'd tried that, or I used "", which didn't work.

**Comment by ruspaul013** [comment]
I also tried with "", but it did not worked.

**Comment by antongisli** [comment]
thx @ruspaul013  - will give that a go.
