### ISSUE TITLE
[Bug] Not enforce API Key to be provided in the sdks when self hosting

### ISSUE THREAD

**Issue by nickscamara** [mendableai/firecrawl#961]
#959

**Comment by RutamBhagat** [comment]
Hi @nickscamara I'd like to help with this issue. Could you share some context to get me started? Any guidance would be great. Thanks!

**Comment by nickscamara** [comment]
Thank you @RutamBhagat! The team is reviewing it!

**Comment by RutamBhagat** [comment]
@nickscamara, perhaps we should keep this issue open until the rust-sdk and python-sdk PRs are merged as well?
